// GENERATED by scripts/build-catalogue.mjs — do not edit by hand.
// Every ladder here passed validation: each step changes exactly one letter,
// no word repeats, and every level has at least one rung to find.
// Levels are ordered easiest first (fewest rungs, then shortest words).

export interface Level {
  id: number
  beginWord: string
  endWord: string
  /** Intermediate words the player must find, in order from begin to end. */
  wordLadder: string[]
}

export const CATALOGUE: Record<"en" | "fr", Level[]> = {
  en: [
  {
    "id": 1,
    "beginWord": "bast",
    "endWord": "beat",
    "wordLadder": [
      "best"
    ]
  },
  {
    "id": 2,
    "beginWord": "bird",
    "endWord": "bond",
    "wordLadder": [
      "bind"
    ]
  },
  {
    "id": 3,
    "beginWord": "cane",
    "endWord": "card",
    "wordLadder": [
      "care"
    ]
  },
  {
    "id": 4,
    "beginWord": "care",
    "endWord": "cash",
    "wordLadder": [
      "case"
    ]
  },
  {
    "id": 5,
    "beginWord": "cart",
    "endWord": "case",
    "wordLadder": [
      "cast"
    ]
  },
  {
    "id": 6,
    "beginWord": "come",
    "endWord": "copy",
    "wordLadder": [
      "cope"
    ]
  },
  {
    "id": 7,
    "beginWord": "corn",
    "endWord": "cure",
    "wordLadder": [
      "core"
    ]
  },
  {
    "id": 8,
    "beginWord": "crow",
    "endWord": "drop",
    "wordLadder": [
      "crop"
    ]
  },
  {
    "id": 9,
    "beginWord": "dare",
    "endWord": "data",
    "wordLadder": [
      "date"
    ]
  },
  {
    "id": 10,
    "beginWord": "darn",
    "endWord": "date",
    "wordLadder": [
      "dare"
    ]
  },
  {
    "id": 11,
    "beginWord": "desk",
    "endWord": "disc",
    "wordLadder": [
      "disk"
    ]
  },
  {
    "id": 12,
    "beginWord": "even",
    "endWord": "over",
    "wordLadder": [
      "ever"
    ]
  },
  {
    "id": 13,
    "beginWord": "feat",
    "endWord": "feed",
    "wordLadder": [
      "feet"
    ]
  },
  {
    "id": 14,
    "beginWord": "feel",
    "endWord": "felt",
    "wordLadder": [
      "fell"
    ]
  },
  {
    "id": 15,
    "beginWord": "fine",
    "endWord": "firm",
    "wordLadder": [
      "fire"
    ]
  },
  {
    "id": 16,
    "beginWord": "food",
    "endWord": "fore",
    "wordLadder": [
      "ford"
    ]
  },
  {
    "id": 17,
    "beginWord": "foot",
    "endWord": "ford",
    "wordLadder": [
      "fort"
    ]
  },
  {
    "id": 18,
    "beginWord": "gold",
    "endWord": "gulf",
    "wordLadder": [
      "golf"
    ]
  },
  {
    "id": 19,
    "beginWord": "golf",
    "endWord": "good",
    "wordLadder": [
      "gold"
    ]
  },
  {
    "id": 20,
    "beginWord": "grey",
    "endWord": "grow",
    "wordLadder": [
      "grew"
    ]
  },
  {
    "id": 21,
    "beginWord": "hand",
    "endWord": "hare",
    "wordLadder": [
      "hard"
    ]
  },
  {
    "id": 22,
    "beginWord": "holy",
    "endWord": "hope",
    "wordLadder": [
      "hole"
    ]
  },
  {
    "id": 23,
    "beginWord": "knee",
    "endWord": "know",
    "wordLadder": [
      "knew"
    ]
  },
  {
    "id": 24,
    "beginWord": "lain",
    "endWord": "land",
    "wordLadder": [
      "laid"
    ]
  },
  {
    "id": 25,
    "beginWord": "lift",
    "endWord": "like",
    "wordLadder": [
      "life"
    ]
  },
  {
    "id": 26,
    "beginWord": "link",
    "endWord": "live",
    "wordLadder": [
      "line"
    ]
  },
  {
    "id": 27,
    "beginWord": "loan",
    "endWord": "lord",
    "wordLadder": [
      "load"
    ]
  },
  {
    "id": 28,
    "beginWord": "lone",
    "endWord": "loss",
    "wordLadder": [
      "lose"
    ]
  },
  {
    "id": 29,
    "beginWord": "long",
    "endWord": "lose",
    "wordLadder": [
      "lone"
    ]
  },
  {
    "id": 30,
    "beginWord": "malt",
    "endWord": "mass",
    "wordLadder": [
      "mast"
    ]
  },
  {
    "id": 31,
    "beginWord": "meal",
    "endWord": "meet",
    "wordLadder": [
      "meat"
    ]
  },
  {
    "id": 32,
    "beginWord": "best",
    "endWord": "bill",
    "wordLadder": [
      "belt",
      "bell"
    ]
  },
  {
    "id": 33,
    "beginWord": "bony",
    "endWord": "born",
    "wordLadder": [
      "bone",
      "bore"
    ]
  },
  {
    "id": 34,
    "beginWord": "burn",
    "endWord": "bush",
    "wordLadder": [
      "bury",
      "busy"
    ]
  },
  {
    "id": 35,
    "beginWord": "cake",
    "endWord": "pine",
    "wordLadder": [
      "cane",
      "pane"
    ]
  },
  {
    "id": 36,
    "beginWord": "code",
    "endWord": "coin",
    "wordLadder": [
      "core",
      "corn"
    ]
  },
  {
    "id": 37,
    "beginWord": "dawn",
    "endWord": "earl",
    "wordLadder": [
      "darn",
      "earn"
    ]
  },
  {
    "id": 38,
    "beginWord": "down",
    "endWord": "earn",
    "wordLadder": [
      "dawn",
      "darn"
    ]
  },
  {
    "id": 39,
    "beginWord": "feet",
    "endWord": "fill",
    "wordLadder": [
      "felt",
      "fell"
    ]
  },
  {
    "id": 40,
    "beginWord": "film",
    "endWord": "find",
    "wordLadder": [
      "file",
      "fine"
    ]
  },
  {
    "id": 41,
    "beginWord": "hang",
    "endWord": "harm",
    "wordLadder": [
      "hand",
      "hard"
    ]
  },
  {
    "id": 42,
    "beginWord": "heal",
    "endWord": "help",
    "wordLadder": [
      "head",
      "held"
    ]
  },
  {
    "id": 43,
    "beginWord": "heat",
    "endWord": "hold",
    "wordLadder": [
      "head",
      "held"
    ]
  },
  {
    "id": 44,
    "beginWord": "kick",
    "endWord": "lack",
    "wordLadder": [
      "pick",
      "pack"
    ]
  },
  {
    "id": 45,
    "beginWord": "line",
    "endWord": "list",
    "wordLadder": [
      "life",
      "lift"
    ]
  },
  {
    "id": 46,
    "beginWord": "luck",
    "endWord": "pace",
    "wordLadder": [
      "lack",
      "pack"
    ]
  },
  {
    "id": 47,
    "beginWord": "mast",
    "endWord": "mate",
    "wordLadder": [
      "malt",
      "male"
    ]
  },
  {
    "id": 48,
    "beginWord": "miss",
    "endWord": "must",
    "wordLadder": [
      "mass",
      "mast"
    ]
  },
  {
    "id": 49,
    "beginWord": "west",
    "endWord": "east",
    "wordLadder": [
      "best",
      "bast"
    ]
  },
  {
    "id": 50,
    "beginWord": "band",
    "endWord": "bare",
    "wordLadder": [
      "hand",
      "hard",
      "hare"
    ]
  },
  {
    "id": 51,
    "beginWord": "base",
    "endWord": "bear",
    "wordLadder": [
      "bast",
      "best",
      "beat"
    ]
  },
  {
    "id": 52,
    "beginWord": "cold",
    "endWord": "warm",
    "wordLadder": [
      "cord",
      "word",
      "ward"
    ]
  },
  {
    "id": 53,
    "beginWord": "core",
    "endWord": "cost",
    "wordLadder": [
      "care",
      "case",
      "cast"
    ]
  },
  {
    "id": 54,
    "beginWord": "else",
    "endWord": "fact",
    "wordLadder": [
      "ease",
      "east",
      "fast"
    ]
  },
  {
    "id": 55,
    "beginWord": "fire",
    "endWord": "fish",
    "wordLadder": [
      "wire",
      "wise",
      "wish"
    ]
  },
  {
    "id": 56,
    "beginWord": "form",
    "endWord": "full",
    "wordLadder": [
      "firm",
      "film",
      "fill"
    ]
  },
  {
    "id": 57,
    "beginWord": "free",
    "endWord": "than",
    "wordLadder": [
      "tree",
      "thee",
      "then"
    ]
  },
  {
    "id": 58,
    "beginWord": "gift",
    "endWord": "give",
    "wordLadder": [
      "lift",
      "life",
      "live"
    ]
  },
  {
    "id": 59,
    "beginWord": "kill",
    "endWord": "kind",
    "wordLadder": [
      "will",
      "wild",
      "wind"
    ]
  },
  {
    "id": 60,
    "beginWord": "lane",
    "endWord": "last",
    "wordLadder": [
      "cane",
      "case",
      "cast"
    ]
  },
  {
    "id": 61,
    "beginWord": "lass",
    "endWord": "male",
    "wordLadder": [
      "mass",
      "mast",
      "malt"
    ]
  },
  {
    "id": 62,
    "beginWord": "late",
    "endWord": "lead",
    "wordLadder": [
      "lane",
      "land",
      "lend"
    ]
  },
  {
    "id": 63,
    "beginWord": "lend",
    "endWord": "life",
    "wordLadder": [
      "land",
      "lane",
      "line"
    ]
  },
  {
    "id": 64,
    "beginWord": "lock",
    "endWord": "mark",
    "wordLadder": [
      "lack",
      "pack",
      "park"
    ]
  },
  {
    "id": 65,
    "beginWord": "love",
    "endWord": "hate",
    "wordLadder": [
      "lone",
      "lane",
      "late"
    ]
  },
  {
    "id": 66,
    "beginWord": "mean",
    "endWord": "near",
    "wordLadder": [
      "meal",
      "deal",
      "dear"
    ]
  },
  {
    "id": 67,
    "beginWord": "milk",
    "endWord": "wine",
    "wordLadder": [
      "mill",
      "will",
      "wile"
    ]
  },
  {
    "id": 68,
    "beginWord": "mind",
    "endWord": "body",
    "wordLadder": [
      "bind",
      "bond",
      "bony"
    ]
  },
  {
    "id": 69,
    "beginWord": "mood",
    "endWord": "more",
    "wordLadder": [
      "food",
      "ford",
      "fore"
    ]
  },
  {
    "id": 70,
    "beginWord": "rise",
    "endWord": "fall",
    "wordLadder": [
      "rile",
      "file",
      "fill"
    ]
  },
  {
    "id": 71,
    "beginWord": "back",
    "endWord": "ball",
    "wordLadder": [
      "bank",
      "tank",
      "talk",
      "tall"
    ]
  },
  {
    "id": 72,
    "beginWord": "book",
    "endWord": "call",
    "wordLadder": [
      "took",
      "tool",
      "toll",
      "tall"
    ]
  },
  {
    "id": 73,
    "beginWord": "bury",
    "endWord": "cage",
    "wordLadder": [
      "burn",
      "barn",
      "bare",
      "care"
    ]
  },
  {
    "id": 74,
    "beginWord": "cast",
    "endWord": "cell",
    "wordLadder": [
      "bast",
      "best",
      "belt",
      "bell"
    ]
  },
  {
    "id": 75,
    "beginWord": "clan",
    "endWord": "fear",
    "wordLadder": [
      "clay",
      "flay",
      "flat",
      "feat"
    ]
  },
  {
    "id": 76,
    "beginWord": "crop",
    "endWord": "gray",
    "wordLadder": [
      "crow",
      "grow",
      "grew",
      "grey"
    ]
  },
  {
    "id": 77,
    "beginWord": "dark",
    "endWord": "lamp",
    "wordLadder": [
      "dare",
      "care",
      "came",
      "camp"
    ]
  },
  {
    "id": 78,
    "beginWord": "deal",
    "endWord": "dull",
    "wordLadder": [
      "teal",
      "tell",
      "fell",
      "full"
    ]
  },
  {
    "id": 79,
    "beginWord": "dish",
    "endWord": "ease",
    "wordLadder": [
      "fish",
      "fist",
      "fast",
      "east"
    ]
  },
  {
    "id": 80,
    "beginWord": "duck",
    "endWord": "face",
    "wordLadder": [
      "luck",
      "lack",
      "pack",
      "pace"
    ]
  },
  {
    "id": 81,
    "beginWord": "fate",
    "endWord": "file",
    "wordLadder": [
      "gate",
      "gave",
      "give",
      "five"
    ]
  },
  {
    "id": 82,
    "beginWord": "flay",
    "endWord": "fuel",
    "wordLadder": [
      "flat",
      "feat",
      "feet",
      "feel"
    ]
  },
  {
    "id": 83,
    "beginWord": "gear",
    "endWord": "goal",
    "wordLadder": [
      "bear",
      "beat",
      "boat",
      "goat"
    ]
  },
  {
    "id": 84,
    "beginWord": "grew",
    "endWord": "plan",
    "wordLadder": [
      "grey",
      "prey",
      "pray",
      "play"
    ]
  },
  {
    "id": 85,
    "beginWord": "hair",
    "endWord": "half",
    "wordLadder": [
      "fair",
      "fail",
      "fall",
      "hall"
    ]
  },
  {
    "id": 86,
    "beginWord": "head",
    "endWord": "tail",
    "wordLadder": [
      "heal",
      "teal",
      "tell",
      "tall"
    ]
  },
  {
    "id": 87,
    "beginWord": "here",
    "endWord": "hole",
    "wordLadder": [
      "mere",
      "more",
      "sore",
      "sole"
    ]
  },
  {
    "id": 88,
    "beginWord": "hire",
    "endWord": "fast",
    "wordLadder": [
      "hare",
      "bare",
      "base",
      "bast"
    ]
  },
  {
    "id": 89,
    "beginWord": "horn",
    "endWord": "jane",
    "wordLadder": [
      "corn",
      "core",
      "care",
      "cane"
    ]
  },
  {
    "id": 90,
    "beginWord": "king",
    "endWord": "laid",
    "wordLadder": [
      "kind",
      "bind",
      "band",
      "land"
    ]
  },
  {
    "id": 91,
    "beginWord": "knew",
    "endWord": "ship",
    "wordLadder": [
      "know",
      "snow",
      "show",
      "shop"
    ]
  },
  {
    "id": 92,
    "beginWord": "left",
    "endWord": "less",
    "wordLadder": [
      "lift",
      "list",
      "last",
      "lass"
    ]
  },
  {
    "id": 93,
    "beginWord": "lost",
    "endWord": "made",
    "wordLadder": [
      "most",
      "mast",
      "malt",
      "male"
    ]
  },
  {
    "id": 94,
    "beginWord": "mail",
    "endWord": "make",
    "wordLadder": [
      "tail",
      "tall",
      "tale",
      "male"
    ]
  },
  {
    "id": 95,
    "beginWord": "main",
    "endWord": "mill",
    "wordLadder": [
      "mail",
      "fail",
      "fall",
      "fill"
    ]
  },
  {
    "id": 96,
    "beginWord": "math",
    "endWord": "mere",
    "wordLadder": [
      "mate",
      "hate",
      "hare",
      "here"
    ]
  },
  {
    "id": 97,
    "beginWord": "meat",
    "endWord": "most",
    "wordLadder": [
      "beat",
      "boat",
      "coat",
      "cost"
    ]
  },
  {
    "id": 98,
    "beginWord": "mine",
    "endWord": "mode",
    "wordLadder": [
      "fine",
      "fire",
      "fore",
      "more"
    ]
  },
  {
    "id": 99,
    "beginWord": "moon",
    "endWord": "port",
    "wordLadder": [
      "mood",
      "food",
      "ford",
      "fort"
    ]
  },
  {
    "id": 100,
    "beginWord": "move",
    "endWord": "myth",
    "wordLadder": [
      "mode",
      "made",
      "mate",
      "math"
    ]
  },
  {
    "id": 101,
    "beginWord": "name",
    "endWord": "nine",
    "wordLadder": [
      "came",
      "cane",
      "lane",
      "line"
    ]
  },
  {
    "id": 102,
    "beginWord": "need",
    "endWord": "peak",
    "wordLadder": [
      "seed",
      "seek",
      "week",
      "weak"
    ]
  },
  {
    "id": 103,
    "beginWord": "nest",
    "endWord": "park",
    "wordLadder": [
      "best",
      "bast",
      "past",
      "part"
    ]
  },
  {
    "id": 104,
    "beginWord": "next",
    "endWord": "part",
    "wordLadder": [
      "nest",
      "best",
      "bast",
      "past"
    ]
  },
  {
    "id": 105,
    "beginWord": "bank",
    "endWord": "barn",
    "wordLadder": [
      "back",
      "pack",
      "park",
      "dark",
      "darn"
    ]
  },
  {
    "id": 106,
    "beginWord": "been",
    "endWord": "bell",
    "wordLadder": [
      "seen",
      "seed",
      "feed",
      "feel",
      "fell"
    ]
  },
  {
    "id": 107,
    "beginWord": "belt",
    "endWord": "bend",
    "wordLadder": [
      "felt",
      "feet",
      "feed",
      "seed",
      "send"
    ]
  },
  {
    "id": 108,
    "beginWord": "bind",
    "endWord": "bite",
    "wordLadder": [
      "wind",
      "wine",
      "wide",
      "side",
      "site"
    ]
  },
  {
    "id": 109,
    "beginWord": "boat",
    "endWord": "bone",
    "wordLadder": [
      "coat",
      "cost",
      "lost",
      "lose",
      "lone"
    ]
  },
  {
    "id": 110,
    "beginWord": "bolt",
    "endWord": "bore",
    "wordLadder": [
      "belt",
      "best",
      "bast",
      "base",
      "bare"
    ]
  },
  {
    "id": 111,
    "beginWord": "busy",
    "endWord": "came",
    "wordLadder": [
      "bury",
      "burn",
      "barn",
      "bare",
      "care"
    ]
  },
  {
    "id": 112,
    "beginWord": "calm",
    "endWord": "camp",
    "wordLadder": [
      "palm",
      "pale",
      "sale",
      "same",
      "came"
    ]
  },
  {
    "id": 113,
    "beginWord": "cent",
    "endWord": "coat",
    "wordLadder": [
      "rent",
      "rest",
      "best",
      "beat",
      "boat"
    ]
  },
  {
    "id": 114,
    "beginWord": "chip",
    "endWord": "flaw",
    "wordLadder": [
      "ship",
      "shop",
      "show",
      "slow",
      "flow"
    ]
  },
  {
    "id": 115,
    "beginWord": "clam",
    "endWord": "dear",
    "wordLadder": [
      "clay",
      "flay",
      "flat",
      "feat",
      "fear"
    ]
  },
  {
    "id": 116,
    "beginWord": "clay",
    "endWord": "dead",
    "wordLadder": [
      "flay",
      "flat",
      "feat",
      "heat",
      "head"
    ]
  },
  {
    "id": 117,
    "beginWord": "clip",
    "endWord": "flow",
    "wordLadder": [
      "slip",
      "ship",
      "shop",
      "show",
      "slow"
    ]
  },
  {
    "id": 118,
    "beginWord": "cook",
    "endWord": "cord",
    "wordLadder": [
      "took",
      "tool",
      "toll",
      "told",
      "cold"
    ]
  },
  {
    "id": 119,
    "beginWord": "cool",
    "endWord": "cope",
    "wordLadder": [
      "tool",
      "toll",
      "roll",
      "role",
      "rope"
    ]
  },
  {
    "id": 120,
    "beginWord": "dial",
    "endWord": "fail",
    "wordLadder": [
      "deal",
      "teal",
      "tell",
      "fell",
      "fall"
    ]
  },
  {
    "id": 121,
    "beginWord": "disk",
    "endWord": "easy",
    "wordLadder": [
      "dish",
      "fish",
      "fist",
      "fast",
      "east"
    ]
  },
  {
    "id": 122,
    "beginWord": "door",
    "endWord": "fell",
    "wordLadder": [
      "poor",
      "pool",
      "tool",
      "toll",
      "tell"
    ]
  },
  {
    "id": 123,
    "beginWord": "fair",
    "endWord": "farm",
    "wordLadder": [
      "fail",
      "fall",
      "fill",
      "film",
      "firm"
    ]
  },
  {
    "id": 124,
    "beginWord": "fist",
    "endWord": "flat",
    "wordLadder": [
      "fast",
      "bast",
      "best",
      "beat",
      "feat"
    ]
  },
  {
    "id": 125,
    "beginWord": "fort",
    "endWord": "gate",
    "wordLadder": [
      "sort",
      "sore",
      "some",
      "same",
      "game"
    ]
  },
  {
    "id": 126,
    "beginWord": "gain",
    "endWord": "gone",
    "wordLadder": [
      "lain",
      "laid",
      "land",
      "lane",
      "lone"
    ]
  },
  {
    "id": 127,
    "beginWord": "gave",
    "endWord": "gene",
    "wordLadder": [
      "give",
      "live",
      "love",
      "lone",
      "gone"
    ]
  },
  {
    "id": 128,
    "beginWord": "goat",
    "endWord": "hall",
    "wordLadder": [
      "boat",
      "beat",
      "belt",
      "bell",
      "ball"
    ]
  },
  {
    "id": 129,
    "beginWord": "have",
    "endWord": "held",
    "wordLadder": [
      "save",
      "sale",
      "sole",
      "hole",
      "hold"
    ]
  },
  {
    "id": 130,
    "beginWord": "hear",
    "endWord": "hill",
    "wordLadder": [
      "bear",
      "beat",
      "belt",
      "bell",
      "bill"
    ]
  },
  {
    "id": 131,
    "beginWord": "hero",
    "endWord": "home",
    "wordLadder": [
      "here",
      "mere",
      "more",
      "core",
      "come"
    ]
  },
  {
    "id": 132,
    "beginWord": "host",
    "endWord": "jack",
    "wordLadder": [
      "post",
      "past",
      "part",
      "park",
      "pack"
    ]
  },
  {
    "id": 133,
    "beginWord": "hour",
    "endWord": "look",
    "wordLadder": [
      "pour",
      "poor",
      "pool",
      "cool",
      "cook"
    ]
  },
  {
    "id": 134,
    "beginWord": "john",
    "endWord": "load",
    "wordLadder": [
      "join",
      "coin",
      "corn",
      "cord",
      "lord"
    ]
  },
  {
    "id": 135,
    "beginWord": "join",
    "endWord": "jury",
    "wordLadder": [
      "coin",
      "corn",
      "born",
      "burn",
      "bury"
    ]
  },
  {
    "id": 136,
    "beginWord": "just",
    "endWord": "lake",
    "wordLadder": [
      "must",
      "mast",
      "cast",
      "case",
      "cake"
    ]
  },
  {
    "id": 137,
    "beginWord": "soft",
    "endWord": "hard",
    "wordLadder": [
      "sort",
      "fort",
      "ford",
      "cord",
      "card"
    ]
  },
  {
    "id": 138,
    "beginWord": "slow",
    "endWord": "fast",
    "wordLadder": [
      "flow",
      "flaw",
      "flat",
      "feat",
      "beat",
      "best",
      "bast"
    ]
  },
  {
    "id": 139,
    "beginWord": "four",
    "endWord": "five",
    "wordLadder": [
      "pour",
      "poor",
      "pool",
      "tool",
      "toll",
      "roll",
      "role",
      "rile",
      "file"
    ]
  },
  {
    "id": 140,
    "beginWord": "game",
    "endWord": "play",
    "wordLadder": [
      "came",
      "case",
      "base",
      "bast",
      "best",
      "beat",
      "feat",
      "flat",
      "flay"
    ]
  }
],
  fr: [
  {
    "id": 1,
    "beginWord": "acme",
    "endWord": "airs",
    "wordLadder": [
      "aime",
      "aire"
    ]
  },
  {
    "id": 2,
    "beginWord": "acre",
    "endWord": "ange",
    "wordLadder": [
      "acte",
      "ante"
    ]
  },
  {
    "id": 3,
    "beginWord": "agee",
    "endWord": "amas",
    "wordLadder": [
      "ages",
      "ames"
    ]
  },
  {
    "id": 4,
    "beginWord": "aide",
    "endWord": "apte",
    "wordLadder": [
      "aire",
      "apre"
    ]
  },
  {
    "id": 5,
    "beginWord": "anse",
    "endWord": "arme",
    "wordLadder": [
      "aise",
      "aime"
    ]
  },
  {
    "id": 6,
    "beginWord": "boom",
    "endWord": "boxe",
    "wordLadder": [
      "boum",
      "boue"
    ]
  },
  {
    "id": 7,
    "beginWord": "bord",
    "endWord": "boys",
    "wordLadder": [
      "bond",
      "bons"
    ]
  },
  {
    "id": 8,
    "beginWord": "caca",
    "endWord": "cela",
    "wordLadder": [
      "coca",
      "cola"
    ]
  },
  {
    "id": 9,
    "beginWord": "chah",
    "endWord": "chez",
    "wordLadder": [
      "char",
      "cher"
    ]
  },
  {
    "id": 10,
    "beginWord": "choc",
    "endWord": "trop",
    "wordLadder": [
      "croc",
      "troc"
    ]
  },
  {
    "id": 11,
    "beginWord": "clef",
    "endWord": "clou",
    "wordLadder": [
      "cles",
      "clos"
    ]
  },
  {
    "id": 12,
    "beginWord": "jack",
    "endWord": "rock",
    "wordLadder": [
      "back",
      "bock"
    ]
  },
  {
    "id": 13,
    "beginWord": "jete",
    "endWord": "jura",
    "wordLadder": [
      "jute",
      "jure"
    ]
  },
  {
    "id": 14,
    "beginWord": "manu",
    "endWord": "meme",
    "wordLadder": [
      "menu",
      "mene"
    ]
  },
  {
    "id": 15,
    "beginWord": "marc",
    "endWord": "mecs",
    "wordLadder": [
      "mars",
      "mers"
    ]
  },
  {
    "id": 16,
    "beginWord": "mark",
    "endWord": "mets",
    "wordLadder": [
      "mars",
      "mers"
    ]
  },
  {
    "id": 17,
    "beginWord": "mary",
    "endWord": "mois",
    "wordLadder": [
      "mars",
      "mais"
    ]
  },
  {
    "id": 18,
    "beginWord": "midi",
    "endWord": "mise",
    "wordLadder": [
      "mini",
      "mine"
    ]
  },
  {
    "id": 19,
    "beginWord": "miel",
    "endWord": "nier",
    "wordLadder": [
      "fiel",
      "fier"
    ]
  },
  {
    "id": 20,
    "beginWord": "neuf",
    "endWord": "yeux",
    "wordLadder": [
      "veuf",
      "veux"
    ]
  },
  {
    "id": 21,
    "beginWord": "noms",
    "endWord": "noye",
    "wordLadder": [
      "nous",
      "noue"
    ]
  },
  {
    "id": 22,
    "beginWord": "nuit",
    "endWord": "ouie",
    "wordLadder": [
      "suit",
      "suie"
    ]
  },
  {
    "id": 23,
    "beginWord": "parc",
    "endWord": "perm",
    "wordLadder": [
      "pari",
      "peri"
    ]
  },
  {
    "id": 24,
    "beginWord": "paru",
    "endWord": "pole",
    "wordLadder": [
      "pare",
      "pale"
    ]
  },
  {
    "id": 25,
    "beginWord": "pays",
    "endWord": "pics",
    "wordLadder": [
      "pans",
      "pins"
    ]
  },
  {
    "id": 26,
    "beginWord": "pope",
    "endWord": "rapt",
    "wordLadder": [
      "pape",
      "rape"
    ]
  },
  {
    "id": 27,
    "beginWord": "pots",
    "endWord": "rets",
    "wordLadder": [
      "mots",
      "mets"
    ]
  },
  {
    "id": 28,
    "beginWord": "rosa",
    "endWord": "roui",
    "wordLadder": [
      "rose",
      "roue"
    ]
  },
  {
    "id": 29,
    "beginWord": "tetu",
    "endWord": "velo",
    "wordLadder": [
      "vetu",
      "veto"
    ]
  },
  {
    "id": 30,
    "beginWord": "trek",
    "endWord": "tuee",
    "wordLadder": [
      "tres",
      "tues"
    ]
  },
  {
    "id": 31,
    "beginWord": "acere",
    "endWord": "alene",
    "wordLadder": [
      "amere",
      "amene"
    ]
  },
  {
    "id": 32,
    "beginWord": "acide",
    "endWord": "bribe",
    "wordLadder": [
      "aride",
      "bride"
    ]
  },
  {
    "id": 33,
    "beginWord": "aider",
    "endWord": "ainee",
    "wordLadder": [
      "aimer",
      "aimee"
    ]
  },
  {
    "id": 34,
    "beginWord": "aides",
    "endWord": "allee",
    "wordLadder": [
      "ailes",
      "alles"
    ]
  },
  {
    "id": 35,
    "beginWord": "aigle",
    "endWord": "digne",
    "wordLadder": [
      "sigle",
      "signe"
    ]
  },
  {
    "id": 36,
    "beginWord": "aigri",
    "endWord": "aille",
    "wordLadder": [
      "aigre",
      "aigle"
    ]
  },
  {
    "id": 37,
    "beginWord": "aines",
    "endWord": "allez",
    "wordLadder": [
      "ailes",
      "alles"
    ]
  },
  {
    "id": 38,
    "beginWord": "algue",
    "endWord": "angle",
    "wordLadder": [
      "aigue",
      "aigle"
    ]
  },
  {
    "id": 39,
    "beginWord": "astre",
    "endWord": "ouvre",
    "wordLadder": [
      "autre",
      "outre"
    ]
  },
  {
    "id": 40,
    "beginWord": "avais",
    "endWord": "ayant",
    "wordLadder": [
      "avait",
      "avant"
    ]
  },
  {
    "id": 41,
    "beginWord": "badge",
    "endWord": "barbu",
    "wordLadder": [
      "barge",
      "barbe"
    ]
  },
  {
    "id": 42,
    "beginWord": "bains",
    "endWord": "coins",
    "wordLadder": [
      "mains",
      "moins"
    ]
  },
  {
    "id": 43,
    "beginWord": "barde",
    "endWord": "beige",
    "wordLadder": [
      "barge",
      "berge"
    ]
  },
  {
    "id": 44,
    "beginWord": "baser",
    "endWord": "cafes",
    "wordLadder": [
      "bases",
      "cases"
    ]
  },
  {
    "id": 45,
    "beginWord": "batir",
    "endWord": "palis",
    "wordLadder": [
      "patir",
      "palir"
    ]
  },
  {
    "id": 46,
    "beginWord": "bette",
    "endWord": "jeter",
    "wordLadder": [
      "jette",
      "jetee"
    ]
  },
  {
    "id": 47,
    "beginWord": "biler",
    "endWord": "caler",
    "wordLadder": [
      "beler",
      "celer"
    ]
  },
  {
    "id": 48,
    "beginWord": "bonds",
    "endWord": "bouee",
    "wordLadder": [
      "bonde",
      "boude"
    ]
  },
  {
    "id": 49,
    "beginWord": "bonne",
    "endWord": "bonus",
    "wordLadder": [
      "bonde",
      "bonds"
    ]
  },
  {
    "id": 50,
    "beginWord": "brame",
    "endWord": "grace",
    "wordLadder": [
      "trame",
      "trace"
    ]
  },
  {
    "id": 51,
    "beginWord": "brule",
    "endWord": "drame",
    "wordLadder": [
      "brume",
      "brame"
    ]
  },
  {
    "id": 52,
    "beginWord": "butte",
    "endWord": "metre",
    "wordLadder": [
      "bette",
      "mette"
    ]
  },
  {
    "id": 53,
    "beginWord": "capes",
    "endWord": "gages",
    "wordLadder": [
      "sapes",
      "sages"
    ]
  },
  {
    "id": 54,
    "beginWord": "casse",
    "endWord": "disse",
    "wordLadder": [
      "lasse",
      "lisse"
    ]
  },
  {
    "id": 55,
    "beginWord": "ceder",
    "endWord": "haler",
    "wordLadder": [
      "celer",
      "heler"
    ]
  },
  {
    "id": 56,
    "beginWord": "amie",
    "endWord": "axee",
    "wordLadder": [
      "amis",
      "ames",
      "axes"
    ]
  },
  {
    "id": 57,
    "beginWord": "asse",
    "endWord": "aube",
    "wordLadder": [
      "aise",
      "aine",
      "aune"
    ]
  },
  {
    "id": 58,
    "beginWord": "avis",
    "endWord": "obus",
    "wordLadder": [
      "anis",
      "anus",
      "abus"
    ]
  },
  {
    "id": 59,
    "beginWord": "bath",
    "endWord": "bete",
    "wordLadder": [
      "bats",
      "buts",
      "bute"
    ]
  },
  {
    "id": 60,
    "beginWord": "bati",
    "endWord": "bure",
    "wordLadder": [
      "bats",
      "buts",
      "bute"
    ]
  },
  {
    "id": 61,
    "beginWord": "beau",
    "endWord": "deca",
    "wordLadder": [
      "veau",
      "vecu",
      "decu"
    ]
  },
  {
    "id": 62,
    "beginWord": "cave",
    "endWord": "city",
    "wordLadder": [
      "came",
      "cime",
      "cite"
    ]
  },
  {
    "id": 63,
    "beginWord": "cent",
    "endWord": "cerf",
    "wordLadder": [
      "sent",
      "sert",
      "serf"
    ]
  },
  {
    "id": 64,
    "beginWord": "emis",
    "endWord": "unes",
    "wordLadder": [
      "amis",
      "anis",
      "unis"
    ]
  },
  {
    "id": 65,
    "beginWord": "flux",
    "endWord": "jean",
    "wordLadder": [
      "feux",
      "jeux",
      "jeun"
    ]
  },
  {
    "id": 66,
    "beginWord": "jade",
    "endWord": "jars",
    "wordLadder": [
      "made",
      "mare",
      "mars"
    ]
  },
  {
    "id": 67,
    "beginWord": "nase",
    "endWord": "noue",
    "wordLadder": [
      "rase",
      "rose",
      "roue"
    ]
  },
  {
    "id": 68,
    "beginWord": "nuls",
    "endWord": "ores",
    "wordLadder": [
      "nues",
      "tues",
      "tres"
    ]
  },
  {
    "id": 69,
    "beginWord": "omis",
    "endWord": "unie",
    "wordLadder": [
      "amis",
      "anis",
      "unis"
    ]
  },
  {
    "id": 70,
    "beginWord": "pans",
    "endWord": "rail",
    "wordLadder": [
      "dans",
      "dais",
      "rais"
    ]
  },
  {
    "id": 71,
    "beginWord": "pape",
    "endWord": "perd",
    "wordLadder": [
      "pare",
      "pari",
      "peri"
    ]
  },
  {
    "id": 72,
    "beginWord": "part",
    "endWord": "pese",
    "wordLadder": [
      "pare",
      "pale",
      "pele"
    ]
  },
  {
    "id": 73,
    "beginWord": "peau",
    "endWord": "rend",
    "wordLadder": [
      "veau",
      "venu",
      "vend"
    ]
  },
  {
    "id": 74,
    "beginWord": "poli",
    "endWord": "rape",
    "wordLadder": [
      "pole",
      "pale",
      "pape"
    ]
  },
  {
    "id": 75,
    "beginWord": "rang",
    "endWord": "secs",
    "wordLadder": [
      "sang",
      "sans",
      "sens"
    ]
  },
  {
    "id": 76,
    "beginWord": "raye",
    "endWord": "rene",
    "wordLadder": [
      "rase",
      "ruse",
      "rune"
    ]
  },
  {
    "id": 77,
    "beginWord": "repu",
    "endWord": "rite",
    "wordLadder": [
      "revu",
      "reve",
      "rive"
    ]
  },
  {
    "id": 78,
    "beginWord": "roux",
    "endWord": "soie",
    "wordLadder": [
      "roue",
      "joue",
      "joie"
    ]
  },
  {
    "id": 79,
    "beginWord": "seau",
    "endWord": "tend",
    "wordLadder": [
      "veau",
      "venu",
      "tenu"
    ]
  },
  {
    "id": 80,
    "beginWord": "sept",
    "endWord": "soif",
    "wordLadder": [
      "sent",
      "sont",
      "soit"
    ]
  },
  {
    "id": 81,
    "beginWord": "tact",
    "endWord": "yang",
    "wordLadder": [
      "tant",
      "gant",
      "gang"
    ]
  },
  {
    "id": 82,
    "beginWord": "time",
    "endWord": "tirs",
    "wordLadder": [
      "aime",
      "aire",
      "airs"
    ]
  },
  {
    "id": 83,
    "beginWord": "tome",
    "endWord": "tort",
    "wordLadder": [
      "dome",
      "dore",
      "dort"
    ]
  },
  {
    "id": 84,
    "beginWord": "tour",
    "endWord": "voue",
    "wordLadder": [
      "tous",
      "nous",
      "noue"
    ]
  },
  {
    "id": 85,
    "beginWord": "agent",
    "endWord": "biens",
    "wordLadder": [
      "aient",
      "tient",
      "tiens"
    ]
  },
  {
    "id": 86,
    "beginWord": "agile",
    "endWord": "edite",
    "wordLadder": [
      "agite",
      "alite",
      "elite"
    ]
  },
  {
    "id": 87,
    "beginWord": "bagne",
    "endWord": "salue",
    "wordLadder": [
      "bague",
      "vague",
      "value"
    ]
  },
  {
    "id": 88,
    "beginWord": "belge",
    "endWord": "garde",
    "wordLadder": [
      "berge",
      "barge",
      "barde"
    ]
  },
  {
    "id": 89,
    "beginWord": "bonde",
    "endWord": "chute",
    "wordLadder": [
      "boude",
      "coude",
      "coute"
    ]
  },
  {
    "id": 90,
    "beginWord": "bords",
    "endWord": "conne",
    "wordLadder": [
      "bonds",
      "bonde",
      "bonne"
    ]
  },
  {
    "id": 91,
    "beginWord": "botte",
    "endWord": "jetes",
    "wordLadder": [
      "bette",
      "jette",
      "jetee"
    ]
  },
  {
    "id": 92,
    "beginWord": "bouts",
    "endWord": "colle",
    "wordLadder": [
      "couts",
      "coute",
      "coule"
    ]
  },
  {
    "id": 93,
    "beginWord": "brune",
    "endWord": "palme",
    "wordLadder": [
      "brume",
      "baume",
      "paume"
    ]
  },
  {
    "id": 94,
    "beginWord": "brute",
    "endWord": "plume",
    "wordLadder": [
      "brume",
      "baume",
      "paume"
    ]
  },
  {
    "id": 95,
    "beginWord": "calin",
    "endWord": "felon",
    "wordLadder": [
      "salin",
      "salon",
      "selon"
    ]
  },
  {
    "id": 96,
    "beginWord": "calme",
    "endWord": "cause",
    "wordLadder": [
      "palme",
      "paume",
      "pause"
    ]
  },
  {
    "id": 97,
    "beginWord": "casus",
    "endWord": "laser",
    "wordLadder": [
      "cases",
      "bases",
      "baser"
    ]
  },
  {
    "id": 98,
    "beginWord": "caves",
    "endWord": "pages",
    "wordLadder": [
      "capes",
      "sapes",
      "sages"
    ]
  },
  {
    "id": 99,
    "beginWord": "celle",
    "endWord": "comte",
    "wordLadder": [
      "colle",
      "coule",
      "coute"
    ]
  },
  {
    "id": 100,
    "beginWord": "cents",
    "endWord": "fonte",
    "wordLadder": [
      "lents",
      "lente",
      "fente"
    ]
  },
  {
    "id": 101,
    "beginWord": "cette",
    "endWord": "tetes",
    "wordLadder": [
      "jette",
      "jetee",
      "jetes"
    ]
  },
  {
    "id": 102,
    "beginWord": "chaos",
    "endWord": "clefs",
    "wordLadder": [
      "chars",
      "chers",
      "chefs"
    ]
  },
  {
    "id": 103,
    "beginWord": "citee",
    "endWord": "dames",
    "wordLadder": [
      "cites",
      "dites",
      "dates"
    ]
  },
  {
    "id": 104,
    "beginWord": "citer",
    "endWord": "datas",
    "wordLadder": [
      "cites",
      "dites",
      "dates"
    ]
  },
  {
    "id": 105,
    "beginWord": "clans",
    "endWord": "plage",
    "wordLadder": [
      "plans",
      "plats",
      "plate"
    ]
  },
  {
    "id": 106,
    "beginWord": "codes",
    "endWord": "datee",
    "wordLadder": [
      "cotes",
      "dotes",
      "dates"
    ]
  },
  {
    "id": 107,
    "beginWord": "colin",
    "endWord": "folie",
    "wordLadder": [
      "colis",
      "jolis",
      "jolie"
    ]
  },
  {
    "id": 108,
    "beginWord": "combe",
    "endWord": "corde",
    "wordLadder": [
      "comte",
      "coute",
      "coude"
    ]
  },
  {
    "id": 109,
    "beginWord": "concu",
    "endWord": "corse",
    "wordLadder": [
      "connu",
      "cornu",
      "corne"
    ]
  },
  {
    "id": 110,
    "beginWord": "conge",
    "endWord": "fonde",
    "wordLadder": [
      "conne",
      "bonne",
      "bonde"
    ]
  },
  {
    "id": 111,
    "beginWord": "bill",
    "endWord": "cafe",
    "wordLadder": [
      "bile",
      "bise",
      "base",
      "case"
    ]
  },
  {
    "id": 112,
    "beginWord": "came",
    "endWord": "cars",
    "wordLadder": [
      "rame",
      "rare",
      "mare",
      "mars"
    ]
  },
  {
    "id": 113,
    "beginWord": "ceux",
    "endWord": "coup",
    "wordLadder": [
      "peux",
      "peur",
      "pour",
      "cour"
    ]
  },
  {
    "id": 114,
    "beginWord": "clan",
    "endWord": "crea",
    "wordLadder": [
      "cran",
      "crin",
      "crie",
      "cree"
    ]
  },
  {
    "id": 115,
    "beginWord": "clin",
    "endWord": "dais",
    "wordLadder": [
      "coin",
      "loin",
      "lois",
      "dois"
    ]
  },
  {
    "id": 116,
    "beginWord": "coma",
    "endWord": "dans",
    "wordLadder": [
      "cola",
      "cols",
      "cons",
      "dons"
    ]
  },
  {
    "id": 117,
    "beginWord": "cout",
    "endWord": "dame",
    "wordLadder": [
      "bout",
      "boue",
      "doue",
      "dome"
    ]
  },
  {
    "id": 118,
    "beginWord": "cuve",
    "endWord": "dira",
    "wordLadder": [
      "cure",
      "pure",
      "pire",
      "dire"
    ]
  },
  {
    "id": 119,
    "beginWord": "dite",
    "endWord": "donc",
    "wordLadder": [
      "dote",
      "dore",
      "dort",
      "dont"
    ]
  },
  {
    "id": 120,
    "beginWord": "doux",
    "endWord": "elle",
    "wordLadder": [
      "doue",
      "moue",
      "mole",
      "mlle"
    ]
  },
  {
    "id": 121,
    "beginWord": "fard",
    "endWord": "faut",
    "wordLadder": [
      "lard",
      "laid",
      "lait",
      "fait"
    ]
  },
  {
    "id": 122,
    "beginWord": "film",
    "endWord": "gene",
    "wordLadder": [
      "file",
      "fine",
      "mine",
      "mene"
    ]
  },
  {
    "id": 123,
    "beginWord": "flot",
    "endWord": "iles",
    "wordLadder": [
      "flou",
      "clou",
      "clos",
      "cles"
    ]
  },
  {
    "id": 124,
    "beginWord": "gant",
    "endWord": "lacs",
    "wordLadder": [
      "gang",
      "sang",
      "sans",
      "sacs"
    ]
  },
  {
    "id": 125,
    "beginWord": "juge",
    "endWord": "lice",
    "wordLadder": [
      "auge",
      "aune",
      "aine",
      "line"
    ]
  },
  {
    "id": 126,
    "beginWord": "maxi",
    "endWord": "nage",
    "wordLadder": [
      "mali",
      "male",
      "pale",
      "page"
    ]
  },
  {
    "id": 127,
    "beginWord": "meuf",
    "endWord": "sauf",
    "wordLadder": [
      "veuf",
      "veut",
      "vaut",
      "saut"
    ]
  },
  {
    "id": 128,
    "beginWord": "mimi",
    "endWord": "pele",
    "wordLadder": [
      "mini",
      "mine",
      "mene",
      "pene"
    ]
  },
  {
    "id": 129,
    "beginWord": "mont",
    "endWord": "naif",
    "wordLadder": [
      "sont",
      "soit",
      "sait",
      "nait"
    ]
  },
  {
    "id": 130,
    "beginWord": "mort",
    "endWord": "nain",
    "wordLadder": [
      "sort",
      "soit",
      "sait",
      "nait"
    ]
  },
  {
    "id": 131,
    "beginWord": "muni",
    "endWord": "pepe",
    "wordLadder": [
      "mini",
      "mine",
      "mene",
      "pene"
    ]
  },
  {
    "id": 132,
    "beginWord": "nets",
    "endWord": "nous",
    "wordLadder": [
      "sets",
      "sens",
      "sons",
      "sous"
    ]
  },
  {
    "id": 133,
    "beginWord": "opte",
    "endWord": "ride",
    "wordLadder": [
      "apte",
      "apre",
      "aire",
      "rire"
    ]
  },
  {
    "id": 134,
    "beginWord": "plan",
    "endWord": "prie",
    "wordLadder": [
      "clan",
      "cran",
      "crin",
      "crie"
    ]
  },
  {
    "id": 135,
    "beginWord": "pres",
    "endWord": "quel",
    "wordLadder": [
      "tres",
      "tues",
      "dues",
      "duel"
    ]
  },
  {
    "id": 136,
    "beginWord": "pull",
    "endWord": "tige",
    "wordLadder": [
      "bull",
      "bill",
      "bile",
      "bige"
    ]
  },
  {
    "id": 137,
    "beginWord": "robe",
    "endWord": "site",
    "wordLadder": [
      "role",
      "dole",
      "dote",
      "dite"
    ]
  },
  {
    "id": 138,
    "beginWord": "sine",
    "endWord": "sure",
    "wordLadder": [
      "aine",
      "aire",
      "pire",
      "pure"
    ]
  },
  {
    "id": 139,
    "beginWord": "soir",
    "endWord": "solo",
    "wordLadder": [
      "soit",
      "sont",
      "sons",
      "sols"
    ]
  },
  {
    "id": 140,
    "beginWord": "surs",
    "endWord": "taie",
    "wordLadder": [
      "suis",
      "sais",
      "rais",
      "raie"
    ]
  },
  {
    "id": 141,
    "beginWord": "tain",
    "endWord": "tari",
    "wordLadder": [
      "main",
      "mais",
      "mars",
      "mari"
    ]
  },
  {
    "id": 142,
    "beginWord": "tard",
    "endWord": "vers",
    "wordLadder": [
      "tari",
      "mari",
      "mars",
      "mers"
    ]
  },
  {
    "id": 143,
    "beginWord": "taxi",
    "endWord": "vole",
    "wordLadder": [
      "maxi",
      "mali",
      "male",
      "mole"
    ]
  },
  {
    "id": 144,
    "beginWord": "test",
    "endWord": "vont",
    "wordLadder": [
      "lest",
      "lent",
      "dent",
      "dont"
    ]
  },
  {
    "id": 145,
    "beginWord": "toux",
    "endWord": "vase",
    "wordLadder": [
      "roux",
      "roue",
      "rose",
      "rase"
    ]
  },
  {
    "id": 146,
    "beginWord": "vamp",
    "endWord": "vise",
    "wordLadder": [
      "camp",
      "came",
      "case",
      "vase"
    ]
  },
  {
    "id": 147,
    "beginWord": "vice",
    "endWord": "vifs",
    "wordLadder": [
      "lice",
      "liee",
      "lies",
      "vies"
    ]
  },
  {
    "id": 148,
    "beginWord": "vint",
    "endWord": "yens",
    "wordLadder": [
      "vont",
      "sont",
      "sent",
      "sens"
    ]
  },
  {
    "id": 149,
    "beginWord": "abces",
    "endWord": "aires",
    "wordLadder": [
      "acces",
      "actes",
      "aptes",
      "apres"
    ]
  },
  {
    "id": 150,
    "beginWord": "aigre",
    "endWord": "fibre",
    "wordLadder": [
      "tigre",
      "titre",
      "litre",
      "libre"
    ]
  },
  {
    "id": 151,
    "beginWord": "aigue",
    "endWord": "livre",
    "wordLadder": [
      "aigre",
      "tigre",
      "titre",
      "litre"
    ]
  },
  {
    "id": 152,
    "beginWord": "aisee",
    "endWord": "allie",
    "wordLadder": [
      "aises",
      "ailes",
      "alles",
      "allee"
    ]
  },
  {
    "id": 153,
    "beginWord": "aloes",
    "endWord": "annee",
    "wordLadder": [
      "alles",
      "ailes",
      "aines",
      "ainee"
    ]
  },
  {
    "id": 154,
    "beginWord": "alors",
    "endWord": "dires",
    "wordLadder": [
      "aloes",
      "alles",
      "ailes",
      "aires"
    ]
  },
  {
    "id": 155,
    "beginWord": "alpes",
    "endWord": "dites",
    "wordLadder": [
      "alles",
      "ailes",
      "aires",
      "dires"
    ]
  },
  {
    "id": 156,
    "beginWord": "aorte",
    "endWord": "arene",
    "wordLadder": [
      "porte",
      "poete",
      "prete",
      "arete"
    ]
  },
  {
    "id": 157,
    "beginWord": "armee",
    "endWord": "files",
    "wordLadder": [
      "aimee",
      "ainee",
      "aines",
      "ailes"
    ]
  },
  {
    "id": 158,
    "beginWord": "armer",
    "endWord": "lires",
    "wordLadder": [
      "aimer",
      "aider",
      "aides",
      "aires"
    ]
  },
  {
    "id": 159,
    "beginWord": "armes",
    "endWord": "mines",
    "wordLadder": [
      "armee",
      "aimee",
      "ainee",
      "aines"
    ]
  },
  {
    "id": 160,
    "beginWord": "asile",
    "endWord": "elime",
    "wordLadder": [
      "agile",
      "agite",
      "alite",
      "elite"
    ]
  },
  {
    "id": 161,
    "beginWord": "avare",
    "endWord": "grene",
    "wordLadder": [
      "avere",
      "amere",
      "amene",
      "arene"
    ]
  },
  {
    "id": 162,
    "beginWord": "balte",
    "endWord": "fente",
    "wordLadder": [
      "halte",
      "hante",
      "sante",
      "sente"
    ]
  },
  {
    "id": 163,
    "beginWord": "basee",
    "endWord": "baume",
    "wordLadder": [
      "basse",
      "passe",
      "pause",
      "paume"
    ]
  },
  {
    "id": 164,
    "beginWord": "bebes",
    "endWord": "beler",
    "wordLadder": [
      "betes",
      "fetes",
      "feter",
      "feler"
    ]
  },
  {
    "id": 165,
    "beginWord": "biere",
    "endWord": "crise",
    "wordLadder": [
      "fiere",
      "frere",
      "frire",
      "frise"
    ]
  },
  {
    "id": 166,
    "beginWord": "aber",
    "endWord": "abus",
    "wordLadder": [
      "amer",
      "ames",
      "amis",
      "anis",
      "anus"
    ]
  },
  {
    "id": 167,
    "beginWord": "acne",
    "endWord": "alle",
    "wordLadder": [
      "aine",
      "mine",
      "mene",
      "mele",
      "mlle"
    ]
  },
  {
    "id": 168,
    "beginWord": "aise",
    "endWord": "aout",
    "wordLadder": [
      "dise",
      "dose",
      "doue",
      "boue",
      "bout"
    ]
  },
  {
    "id": 169,
    "beginWord": "auge",
    "endWord": "baie",
    "wordLadder": [
      "ange",
      "anse",
      "aise",
      "bise",
      "base"
    ]
  },
  {
    "id": 170,
    "beginWord": "bain",
    "endWord": "banc",
    "wordLadder": [
      "sain",
      "sais",
      "sans",
      "sang",
      "bang"
    ]
  },
  {
    "id": 171,
    "beginWord": "bars",
    "endWord": "bave",
    "wordLadder": [
      "mars",
      "mais",
      "rais",
      "raie",
      "baie"
    ]
  },
  {
    "id": 172,
    "beginWord": "best",
    "endWord": "bons",
    "wordLadder": [
      "lest",
      "lent",
      "dent",
      "dont",
      "dons"
    ]
  },
  {
    "id": 173,
    "beginWord": "bige",
    "endWord": "bouc",
    "wordLadder": [
      "bise",
      "dise",
      "dose",
      "doue",
      "boue"
    ]
  },
  {
    "id": 174,
    "beginWord": "bile",
    "endWord": "boum",
    "wordLadder": [
      "bise",
      "dise",
      "dose",
      "doue",
      "boue"
    ]
  },
  {
    "id": 175,
    "beginWord": "bond",
    "endWord": "brut",
    "wordLadder": [
      "bons",
      "tons",
      "tous",
      "tout",
      "bout"
    ]
  },
  {
    "id": 176,
    "beginWord": "brun",
    "endWord": "cons",
    "wordLadder": [
      "brut",
      "bout",
      "tout",
      "tous",
      "tons"
    ]
  },
  {
    "id": 177,
    "beginWord": "bull",
    "endWord": "cake",
    "wordLadder": [
      "bill",
      "bile",
      "bise",
      "base",
      "case"
    ]
  },
  {
    "id": 178,
    "beginWord": "camp",
    "endWord": "cede",
    "wordLadder": [
      "came",
      "cime",
      "cite",
      "cote",
      "code"
    ]
  },
  {
    "id": 179,
    "beginWord": "cils",
    "endWord": "coin",
    "wordLadder": [
      "cols",
      "vols",
      "vois",
      "lois",
      "loin"
    ]
  },
  {
    "id": 180,
    "beginWord": "cris",
    "endWord": "doit",
    "wordLadder": [
      "pris",
      "prix",
      "poix",
      "voix",
      "voit"
    ]
  },
  {
    "id": 181,
    "beginWord": "cube",
    "endWord": "data",
    "wordLadder": [
      "cure",
      "pure",
      "pare",
      "pate",
      "date"
    ]
  },
  {
    "id": 182,
    "beginWord": "cuir",
    "endWord": "dort",
    "wordLadder": [
      "fuir",
      "fuit",
      "suit",
      "soit",
      "doit"
    ]
  },
  {
    "id": 183,
    "beginWord": "defi",
    "endWord": "fete",
    "wordLadder": [
      "demi",
      "semi",
      "seme",
      "seve",
      "feve"
    ]
  },
  {
    "id": 184,
    "beginWord": "deja",
    "endWord": "leve",
    "wordLadder": [
      "deca",
      "decu",
      "recu",
      "revu",
      "reve"
    ]
  },
  {
    "id": 185,
    "beginWord": "dits",
    "endWord": "dodo",
    "wordLadder": [
      "lits",
      "lots",
      "mots",
      "moto",
      "modo"
    ]
  },
  {
    "id": 186,
    "beginWord": "dole",
    "endWord": "dues",
    "wordLadder": [
      "role",
      "rose",
      "ruse",
      "ruee",
      "rues"
    ]
  },
  {
    "id": 187,
    "beginWord": "duel",
    "endWord": "fais",
    "wordLadder": [
      "dues",
      "durs",
      "murs",
      "mars",
      "mais"
    ]
  },
  {
    "id": 188,
    "beginWord": "duos",
    "endWord": "dupe",
    "wordLadder": [
      "durs",
      "purs",
      "pure",
      "jure",
      "jupe"
    ]
  },
  {
    "id": 189,
    "beginWord": "ecus",
    "endWord": "gele",
    "wordLadder": [
      "elus",
      "elue",
      "elle",
      "mlle",
      "mele"
    ]
  },
  {
    "id": 190,
    "beginWord": "elan",
    "endWord": "fois",
    "wordLadder": [
      "clan",
      "clin",
      "coin",
      "loin",
      "lois"
    ]
  },
  {
    "id": 191,
    "beginWord": "fada",
    "endWord": "faim",
    "wordLadder": [
      "fade",
      "rade",
      "raie",
      "rais",
      "fais"
    ]
  },
  {
    "id": 192,
    "beginWord": "fado",
    "endWord": "fait",
    "wordLadder": [
      "fade",
      "rade",
      "raie",
      "rais",
      "fais"
    ]
  },
  {
    "id": 193,
    "beginWord": "fees",
    "endWord": "fins",
    "wordLadder": [
      "nees",
      "nues",
      "vues",
      "vies",
      "vins"
    ]
  },
  {
    "id": 194,
    "beginWord": "fera",
    "endWord": "fond",
    "wordLadder": [
      "sera",
      "sert",
      "sort",
      "sont",
      "font"
    ]
  },
  {
    "id": 195,
    "beginWord": "fers",
    "endWord": "fous",
    "wordLadder": [
      "mers",
      "mars",
      "mais",
      "fais",
      "fois"
    ]
  },
  {
    "id": 196,
    "beginWord": "feux",
    "endWord": "gout",
    "wordLadder": [
      "peux",
      "peur",
      "pour",
      "cour",
      "cout"
    ]
  },
  {
    "id": 197,
    "beginWord": "fief",
    "endWord": "fige",
    "wordLadder": [
      "fier",
      "lier",
      "liee",
      "line",
      "fine"
    ]
  },
  {
    "id": 198,
    "beginWord": "fiel",
    "endWord": "file",
    "wordLadder": [
      "fier",
      "lier",
      "liee",
      "line",
      "fine"
    ]
  },
  {
    "id": 199,
    "beginWord": "fils",
    "endWord": "gain",
    "wordLadder": [
      "fins",
      "vins",
      "vans",
      "vais",
      "vain"
    ]
  },
  {
    "id": 200,
    "beginWord": "fret",
    "endWord": "hair",
    "wordLadder": [
      "pret",
      "prit",
      "prix",
      "paix",
      "pair"
    ]
  },
  {
    "id": 201,
    "beginWord": "fute",
    "endWord": "gage",
    "wordLadder": [
      "bute",
      "bure",
      "pure",
      "pare",
      "page"
    ]
  },
  {
    "id": 202,
    "beginWord": "futs",
    "endWord": "haie",
    "wordLadder": [
      "buts",
      "bats",
      "rats",
      "rais",
      "raie"
    ]
  },
  {
    "id": 203,
    "beginWord": "gala",
    "endWord": "hate",
    "wordLadder": [
      "gaza",
      "gaze",
      "gage",
      "page",
      "pate"
    ]
  },
  {
    "id": 204,
    "beginWord": "gang",
    "endWord": "huit",
    "wordLadder": [
      "sang",
      "sans",
      "sais",
      "suis",
      "suit"
    ]
  },
  {
    "id": 205,
    "beginWord": "glue",
    "endWord": "iris",
    "wordLadder": [
      "elue",
      "elus",
      "plus",
      "plis",
      "pris"
    ]
  },
  {
    "id": 206,
    "beginWord": "grue",
    "endWord": "made",
    "wordLadder": [
      "glue",
      "elue",
      "elle",
      "mlle",
      "male"
    ]
  },
  {
    "id": 207,
    "beginWord": "have",
    "endWord": "hier",
    "wordLadder": [
      "lave",
      "lame",
      "lime",
      "liee",
      "lier"
    ]
  },
  {
    "id": 208,
    "beginWord": "inde",
    "endWord": "joie",
    "wordLadder": [
      "iode",
      "code",
      "cote",
      "vote",
      "voie"
    ]
  },
  {
    "id": 209,
    "beginWord": "inne",
    "endWord": "noce",
    "wordLadder": [
      "inde",
      "iode",
      "code",
      "cote",
      "note"
    ]
  },
  {
    "id": 210,
    "beginWord": "joua",
    "endWord": "lama",
    "wordLadder": [
      "joue",
      "doue",
      "dome",
      "dame",
      "lame"
    ]
  },
  {
    "id": 211,
    "beginWord": "joug",
    "endWord": "laye",
    "wordLadder": [
      "joue",
      "doue",
      "dome",
      "dame",
      "lame"
    ]
  },
  {
    "id": 212,
    "beginWord": "juan",
    "endWord": "leur",
    "wordLadder": [
      "jean",
      "jeun",
      "jeux",
      "peux",
      "peur"
    ]
  },
  {
    "id": 213,
    "beginWord": "juin",
    "endWord": "peut",
    "wordLadder": [
      "juan",
      "jean",
      "jeun",
      "jeux",
      "peux"
    ]
  },
  {
    "id": 214,
    "beginWord": "jury",
    "endWord": "lies",
    "wordLadder": [
      "jure",
      "pure",
      "pire",
      "lire",
      "liee"
    ]
  },
  {
    "id": 215,
    "beginWord": "laic",
    "endWord": "laps",
    "wordLadder": [
      "lait",
      "sait",
      "sais",
      "sacs",
      "lacs"
    ]
  },
  {
    "id": 216,
    "beginWord": "land",
    "endWord": "loir",
    "wordLadder": [
      "laid",
      "raid",
      "rais",
      "rois",
      "lois"
    ]
  },
  {
    "id": 217,
    "beginWord": "life",
    "endWord": "logo",
    "wordLadder": [
      "liee",
      "lies",
      "lits",
      "lots",
      "loto"
    ]
  },
  {
    "id": 218,
    "beginWord": "lima",
    "endWord": "loue",
    "wordLadder": [
      "lama",
      "lame",
      "dame",
      "dome",
      "doue"
    ]
  },
  {
    "id": 219,
    "beginWord": "lord",
    "endWord": "main",
    "wordLadder": [
      "lard",
      "laid",
      "raid",
      "rais",
      "mais"
    ]
  },
  {
    "id": 220,
    "beginWord": "luis",
    "endWord": "mali",
    "wordLadder": [
      "suis",
      "sais",
      "mais",
      "mars",
      "mari"
    ]
  }
],
}
