// GENERATED by scripts/build-catalogue.mjs — do not edit by hand.
// Every ladder here passed validation: each step changes exactly one letter,
// no word repeats, and every level has at least one rung to find.
// Levels are ordered easiest first (fewest rungs, then shortest words).

export interface Level {
  id: number
  beginWord: string
  endWord: string
  /** Intermediate words the player must find, in order from begin to end. */
  wordLadder: string[]
}

export const CATALOGUE: Record<"en" | "fr", Level[]> = {
  en: [
  {
    "id": 1,
    "beginWord": "bast",
    "endWord": "beat",
    "wordLadder": [
      "best"
    ]
  },
  {
    "id": 2,
    "beginWord": "bird",
    "endWord": "bond",
    "wordLadder": [
      "bind"
    ]
  },
  {
    "id": 3,
    "beginWord": "cane",
    "endWord": "card",
    "wordLadder": [
      "care"
    ]
  },
  {
    "id": 4,
    "beginWord": "care",
    "endWord": "cash",
    "wordLadder": [
      "case"
    ]
  },
  {
    "id": 5,
    "beginWord": "cart",
    "endWord": "case",
    "wordLadder": [
      "cast"
    ]
  },
  {
    "id": 6,
    "beginWord": "come",
    "endWord": "copy",
    "wordLadder": [
      "cope"
    ]
  },
  {
    "id": 7,
    "beginWord": "corn",
    "endWord": "cure",
    "wordLadder": [
      "core"
    ]
  },
  {
    "id": 8,
    "beginWord": "crow",
    "endWord": "drop",
    "wordLadder": [
      "crop"
    ]
  },
  {
    "id": 9,
    "beginWord": "dare",
    "endWord": "data",
    "wordLadder": [
      "date"
    ]
  },
  {
    "id": 10,
    "beginWord": "darn",
    "endWord": "date",
    "wordLadder": [
      "dare"
    ]
  },
  {
    "id": 11,
    "beginWord": "desk",
    "endWord": "disc",
    "wordLadder": [
      "disk"
    ]
  },
  {
    "id": 12,
    "beginWord": "even",
    "endWord": "over",
    "wordLadder": [
      "ever"
    ]
  },
  {
    "id": 13,
    "beginWord": "feat",
    "endWord": "feed",
    "wordLadder": [
      "feet"
    ]
  },
  {
    "id": 14,
    "beginWord": "feel",
    "endWord": "felt",
    "wordLadder": [
      "fell"
    ]
  },
  {
    "id": 15,
    "beginWord": "fine",
    "endWord": "firm",
    "wordLadder": [
      "fire"
    ]
  },
  {
    "id": 16,
    "beginWord": "food",
    "endWord": "fore",
    "wordLadder": [
      "ford"
    ]
  },
  {
    "id": 17,
    "beginWord": "foot",
    "endWord": "ford",
    "wordLadder": [
      "fort"
    ]
  },
  {
    "id": 18,
    "beginWord": "gold",
    "endWord": "gulf",
    "wordLadder": [
      "golf"
    ]
  },
  {
    "id": 19,
    "beginWord": "golf",
    "endWord": "good",
    "wordLadder": [
      "gold"
    ]
  },
  {
    "id": 20,
    "beginWord": "grey",
    "endWord": "grow",
    "wordLadder": [
      "grew"
    ]
  },
  {
    "id": 21,
    "beginWord": "hand",
    "endWord": "hare",
    "wordLadder": [
      "hard"
    ]
  },
  {
    "id": 22,
    "beginWord": "holy",
    "endWord": "hope",
    "wordLadder": [
      "hole"
    ]
  },
  {
    "id": 23,
    "beginWord": "knee",
    "endWord": "know",
    "wordLadder": [
      "knew"
    ]
  },
  {
    "id": 24,
    "beginWord": "lain",
    "endWord": "land",
    "wordLadder": [
      "laid"
    ]
  },
  {
    "id": 25,
    "beginWord": "lift",
    "endWord": "like",
    "wordLadder": [
      "life"
    ]
  },
  {
    "id": 26,
    "beginWord": "link",
    "endWord": "live",
    "wordLadder": [
      "line"
    ]
  },
  {
    "id": 27,
    "beginWord": "loan",
    "endWord": "lord",
    "wordLadder": [
      "load"
    ]
  },
  {
    "id": 28,
    "beginWord": "lone",
    "endWord": "loss",
    "wordLadder": [
      "lose"
    ]
  },
  {
    "id": 29,
    "beginWord": "long",
    "endWord": "lose",
    "wordLadder": [
      "lone"
    ]
  },
  {
    "id": 30,
    "beginWord": "malt",
    "endWord": "mass",
    "wordLadder": [
      "mast"
    ]
  },
  {
    "id": 31,
    "beginWord": "meal",
    "endWord": "meet",
    "wordLadder": [
      "meat"
    ]
  },
  {
    "id": 32,
    "beginWord": "best",
    "endWord": "bill",
    "wordLadder": [
      "belt",
      "bell"
    ]
  },
  {
    "id": 33,
    "beginWord": "bony",
    "endWord": "born",
    "wordLadder": [
      "bone",
      "bore"
    ]
  },
  {
    "id": 34,
    "beginWord": "burn",
    "endWord": "bush",
    "wordLadder": [
      "bury",
      "busy"
    ]
  },
  {
    "id": 35,
    "beginWord": "cake",
    "endWord": "pine",
    "wordLadder": [
      "cane",
      "pane"
    ]
  },
  {
    "id": 36,
    "beginWord": "code",
    "endWord": "coin",
    "wordLadder": [
      "core",
      "corn"
    ]
  },
  {
    "id": 37,
    "beginWord": "dawn",
    "endWord": "earl",
    "wordLadder": [
      "darn",
      "earn"
    ]
  },
  {
    "id": 38,
    "beginWord": "down",
    "endWord": "earn",
    "wordLadder": [
      "dawn",
      "darn"
    ]
  },
  {
    "id": 39,
    "beginWord": "feet",
    "endWord": "fill",
    "wordLadder": [
      "felt",
      "fell"
    ]
  },
  {
    "id": 40,
    "beginWord": "film",
    "endWord": "find",
    "wordLadder": [
      "file",
      "fine"
    ]
  },
  {
    "id": 41,
    "beginWord": "hang",
    "endWord": "harm",
    "wordLadder": [
      "hand",
      "hard"
    ]
  },
  {
    "id": 42,
    "beginWord": "heal",
    "endWord": "help",
    "wordLadder": [
      "head",
      "held"
    ]
  },
  {
    "id": 43,
    "beginWord": "heat",
    "endWord": "hold",
    "wordLadder": [
      "head",
      "held"
    ]
  },
  {
    "id": 44,
    "beginWord": "kick",
    "endWord": "lack",
    "wordLadder": [
      "pick",
      "pack"
    ]
  },
  {
    "id": 45,
    "beginWord": "line",
    "endWord": "list",
    "wordLadder": [
      "life",
      "lift"
    ]
  },
  {
    "id": 46,
    "beginWord": "luck",
    "endWord": "pace",
    "wordLadder": [
      "lack",
      "pack"
    ]
  },
  {
    "id": 47,
    "beginWord": "mast",
    "endWord": "mate",
    "wordLadder": [
      "malt",
      "male"
    ]
  },
  {
    "id": 48,
    "beginWord": "miss",
    "endWord": "must",
    "wordLadder": [
      "mass",
      "mast"
    ]
  },
  {
    "id": 49,
    "beginWord": "west",
    "endWord": "east",
    "wordLadder": [
      "best",
      "bast"
    ]
  },
  {
    "id": 50,
    "beginWord": "band",
    "endWord": "bare",
    "wordLadder": [
      "hand",
      "hard",
      "hare"
    ]
  },
  {
    "id": 51,
    "beginWord": "base",
    "endWord": "bear",
    "wordLadder": [
      "bast",
      "best",
      "beat"
    ]
  },
  {
    "id": 52,
    "beginWord": "cold",
    "endWord": "warm",
    "wordLadder": [
      "cord",
      "word",
      "ward"
    ]
  },
  {
    "id": 53,
    "beginWord": "core",
    "endWord": "cost",
    "wordLadder": [
      "care",
      "case",
      "cast"
    ]
  },
  {
    "id": 54,
    "beginWord": "else",
    "endWord": "fact",
    "wordLadder": [
      "ease",
      "east",
      "fast"
    ]
  },
  {
    "id": 55,
    "beginWord": "fire",
    "endWord": "fish",
    "wordLadder": [
      "wire",
      "wise",
      "wish"
    ]
  },
  {
    "id": 56,
    "beginWord": "form",
    "endWord": "full",
    "wordLadder": [
      "firm",
      "film",
      "fill"
    ]
  },
  {
    "id": 57,
    "beginWord": "free",
    "endWord": "than",
    "wordLadder": [
      "tree",
      "thee",
      "then"
    ]
  },
  {
    "id": 58,
    "beginWord": "gift",
    "endWord": "give",
    "wordLadder": [
      "lift",
      "life",
      "live"
    ]
  },
  {
    "id": 59,
    "beginWord": "kill",
    "endWord": "kind",
    "wordLadder": [
      "will",
      "wild",
      "wind"
    ]
  },
  {
    "id": 60,
    "beginWord": "lane",
    "endWord": "last",
    "wordLadder": [
      "cane",
      "case",
      "cast"
    ]
  },
  {
    "id": 61,
    "beginWord": "lass",
    "endWord": "male",
    "wordLadder": [
      "mass",
      "mast",
      "malt"
    ]
  },
  {
    "id": 62,
    "beginWord": "late",
    "endWord": "lead",
    "wordLadder": [
      "lane",
      "land",
      "lend"
    ]
  },
  {
    "id": 63,
    "beginWord": "lend",
    "endWord": "life",
    "wordLadder": [
      "land",
      "lane",
      "line"
    ]
  },
  {
    "id": 64,
    "beginWord": "lock",
    "endWord": "mark",
    "wordLadder": [
      "lack",
      "pack",
      "park"
    ]
  },
  {
    "id": 65,
    "beginWord": "love",
    "endWord": "hate",
    "wordLadder": [
      "lone",
      "lane",
      "late"
    ]
  },
  {
    "id": 66,
    "beginWord": "mean",
    "endWord": "near",
    "wordLadder": [
      "meal",
      "deal",
      "dear"
    ]
  },
  {
    "id": 67,
    "beginWord": "milk",
    "endWord": "wine",
    "wordLadder": [
      "mill",
      "will",
      "wile"
    ]
  },
  {
    "id": 68,
    "beginWord": "mind",
    "endWord": "body",
    "wordLadder": [
      "bind",
      "bond",
      "bony"
    ]
  },
  {
    "id": 69,
    "beginWord": "mood",
    "endWord": "more",
    "wordLadder": [
      "food",
      "ford",
      "fore"
    ]
  },
  {
    "id": 70,
    "beginWord": "rise",
    "endWord": "fall",
    "wordLadder": [
      "rile",
      "file",
      "fill"
    ]
  },
  {
    "id": 71,
    "beginWord": "back",
    "endWord": "ball",
    "wordLadder": [
      "bank",
      "tank",
      "talk",
      "tall"
    ]
  },
  {
    "id": 72,
    "beginWord": "book",
    "endWord": "call",
    "wordLadder": [
      "took",
      "tool",
      "toll",
      "tall"
    ]
  },
  {
    "id": 73,
    "beginWord": "bury",
    "endWord": "cage",
    "wordLadder": [
      "burn",
      "barn",
      "bare",
      "care"
    ]
  },
  {
    "id": 74,
    "beginWord": "cast",
    "endWord": "cell",
    "wordLadder": [
      "bast",
      "best",
      "belt",
      "bell"
    ]
  },
  {
    "id": 75,
    "beginWord": "clan",
    "endWord": "fear",
    "wordLadder": [
      "clay",
      "flay",
      "flat",
      "feat"
    ]
  },
  {
    "id": 76,
    "beginWord": "crop",
    "endWord": "gray",
    "wordLadder": [
      "crow",
      "grow",
      "grew",
      "grey"
    ]
  },
  {
    "id": 77,
    "beginWord": "dark",
    "endWord": "lamp",
    "wordLadder": [
      "dare",
      "care",
      "came",
      "camp"
    ]
  },
  {
    "id": 78,
    "beginWord": "deal",
    "endWord": "dull",
    "wordLadder": [
      "teal",
      "tell",
      "fell",
      "full"
    ]
  },
  {
    "id": 79,
    "beginWord": "dish",
    "endWord": "ease",
    "wordLadder": [
      "fish",
      "fist",
      "fast",
      "east"
    ]
  },
  {
    "id": 80,
    "beginWord": "duck",
    "endWord": "face",
    "wordLadder": [
      "luck",
      "lack",
      "pack",
      "pace"
    ]
  },
  {
    "id": 81,
    "beginWord": "fate",
    "endWord": "file",
    "wordLadder": [
      "gate",
      "gave",
      "give",
      "five"
    ]
  },
  {
    "id": 82,
    "beginWord": "flay",
    "endWord": "fuel",
    "wordLadder": [
      "flat",
      "feat",
      "feet",
      "feel"
    ]
  },
  {
    "id": 83,
    "beginWord": "gear",
    "endWord": "goal",
    "wordLadder": [
      "bear",
      "beat",
      "boat",
      "goat"
    ]
  },
  {
    "id": 84,
    "beginWord": "grew",
    "endWord": "plan",
    "wordLadder": [
      "grey",
      "prey",
      "pray",
      "play"
    ]
  },
  {
    "id": 85,
    "beginWord": "hair",
    "endWord": "half",
    "wordLadder": [
      "fair",
      "fail",
      "fall",
      "hall"
    ]
  },
  {
    "id": 86,
    "beginWord": "head",
    "endWord": "tail",
    "wordLadder": [
      "heal",
      "teal",
      "tell",
      "tall"
    ]
  },
  {
    "id": 87,
    "beginWord": "here",
    "endWord": "hole",
    "wordLadder": [
      "mere",
      "more",
      "sore",
      "sole"
    ]
  },
  {
    "id": 88,
    "beginWord": "hire",
    "endWord": "fast",
    "wordLadder": [
      "hare",
      "bare",
      "base",
      "bast"
    ]
  },
  {
    "id": 89,
    "beginWord": "horn",
    "endWord": "jane",
    "wordLadder": [
      "corn",
      "core",
      "care",
      "cane"
    ]
  },
  {
    "id": 90,
    "beginWord": "king",
    "endWord": "laid",
    "wordLadder": [
      "kind",
      "bind",
      "band",
      "land"
    ]
  },
  {
    "id": 91,
    "beginWord": "knew",
    "endWord": "ship",
    "wordLadder": [
      "know",
      "snow",
      "show",
      "shop"
    ]
  },
  {
    "id": 92,
    "beginWord": "left",
    "endWord": "less",
    "wordLadder": [
      "lift",
      "list",
      "last",
      "lass"
    ]
  },
  {
    "id": 93,
    "beginWord": "lost",
    "endWord": "made",
    "wordLadder": [
      "most",
      "mast",
      "malt",
      "male"
    ]
  },
  {
    "id": 94,
    "beginWord": "mail",
    "endWord": "make",
    "wordLadder": [
      "tail",
      "tall",
      "tale",
      "male"
    ]
  },
  {
    "id": 95,
    "beginWord": "main",
    "endWord": "mill",
    "wordLadder": [
      "mail",
      "fail",
      "fall",
      "fill"
    ]
  },
  {
    "id": 96,
    "beginWord": "math",
    "endWord": "mere",
    "wordLadder": [
      "mate",
      "hate",
      "hare",
      "here"
    ]
  },
  {
    "id": 97,
    "beginWord": "meat",
    "endWord": "most",
    "wordLadder": [
      "beat",
      "boat",
      "coat",
      "cost"
    ]
  },
  {
    "id": 98,
    "beginWord": "mine",
    "endWord": "mode",
    "wordLadder": [
      "fine",
      "fire",
      "fore",
      "more"
    ]
  },
  {
    "id": 99,
    "beginWord": "moon",
    "endWord": "port",
    "wordLadder": [
      "mood",
      "food",
      "ford",
      "fort"
    ]
  },
  {
    "id": 100,
    "beginWord": "move",
    "endWord": "myth",
    "wordLadder": [
      "mode",
      "made",
      "mate",
      "math"
    ]
  },
  {
    "id": 101,
    "beginWord": "name",
    "endWord": "nine",
    "wordLadder": [
      "came",
      "cane",
      "lane",
      "line"
    ]
  },
  {
    "id": 102,
    "beginWord": "need",
    "endWord": "peak",
    "wordLadder": [
      "seed",
      "seek",
      "week",
      "weak"
    ]
  },
  {
    "id": 103,
    "beginWord": "nest",
    "endWord": "park",
    "wordLadder": [
      "best",
      "bast",
      "past",
      "part"
    ]
  },
  {
    "id": 104,
    "beginWord": "next",
    "endWord": "part",
    "wordLadder": [
      "nest",
      "best",
      "bast",
      "past"
    ]
  },
  {
    "id": 105,
    "beginWord": "bank",
    "endWord": "barn",
    "wordLadder": [
      "back",
      "pack",
      "park",
      "dark",
      "darn"
    ]
  },
  {
    "id": 106,
    "beginWord": "been",
    "endWord": "bell",
    "wordLadder": [
      "seen",
      "seed",
      "feed",
      "feel",
      "fell"
    ]
  },
  {
    "id": 107,
    "beginWord": "belt",
    "endWord": "bend",
    "wordLadder": [
      "felt",
      "feet",
      "feed",
      "seed",
      "send"
    ]
  },
  {
    "id": 108,
    "beginWord": "bind",
    "endWord": "bite",
    "wordLadder": [
      "wind",
      "wine",
      "wide",
      "side",
      "site"
    ]
  },
  {
    "id": 109,
    "beginWord": "boat",
    "endWord": "bone",
    "wordLadder": [
      "coat",
      "cost",
      "lost",
      "lose",
      "lone"
    ]
  },
  {
    "id": 110,
    "beginWord": "bolt",
    "endWord": "bore",
    "wordLadder": [
      "belt",
      "best",
      "bast",
      "base",
      "bare"
    ]
  },
  {
    "id": 111,
    "beginWord": "busy",
    "endWord": "came",
    "wordLadder": [
      "bury",
      "burn",
      "barn",
      "bare",
      "care"
    ]
  },
  {
    "id": 112,
    "beginWord": "calm",
    "endWord": "camp",
    "wordLadder": [
      "palm",
      "pale",
      "sale",
      "same",
      "came"
    ]
  },
  {
    "id": 113,
    "beginWord": "cent",
    "endWord": "coat",
    "wordLadder": [
      "rent",
      "rest",
      "best",
      "beat",
      "boat"
    ]
  },
  {
    "id": 114,
    "beginWord": "chip",
    "endWord": "flaw",
    "wordLadder": [
      "ship",
      "shop",
      "show",
      "slow",
      "flow"
    ]
  },
  {
    "id": 115,
    "beginWord": "clam",
    "endWord": "dear",
    "wordLadder": [
      "clay",
      "flay",
      "flat",
      "feat",
      "fear"
    ]
  },
  {
    "id": 116,
    "beginWord": "clay",
    "endWord": "dead",
    "wordLadder": [
      "flay",
      "flat",
      "feat",
      "heat",
      "head"
    ]
  },
  {
    "id": 117,
    "beginWord": "clip",
    "endWord": "flow",
    "wordLadder": [
      "slip",
      "ship",
      "shop",
      "show",
      "slow"
    ]
  },
  {
    "id": 118,
    "beginWord": "cook",
    "endWord": "cord",
    "wordLadder": [
      "took",
      "tool",
      "toll",
      "told",
      "cold"
    ]
  },
  {
    "id": 119,
    "beginWord": "cool",
    "endWord": "cope",
    "wordLadder": [
      "tool",
      "toll",
      "roll",
      "role",
      "rope"
    ]
  },
  {
    "id": 120,
    "beginWord": "dial",
    "endWord": "fail",
    "wordLadder": [
      "deal",
      "teal",
      "tell",
      "fell",
      "fall"
    ]
  },
  {
    "id": 121,
    "beginWord": "disk",
    "endWord": "easy",
    "wordLadder": [
      "dish",
      "fish",
      "fist",
      "fast",
      "east"
    ]
  },
  {
    "id": 122,
    "beginWord": "door",
    "endWord": "fell",
    "wordLadder": [
      "poor",
      "pool",
      "tool",
      "toll",
      "tell"
    ]
  },
  {
    "id": 123,
    "beginWord": "fair",
    "endWord": "farm",
    "wordLadder": [
      "fail",
      "fall",
      "fill",
      "film",
      "firm"
    ]
  },
  {
    "id": 124,
    "beginWord": "fist",
    "endWord": "flat",
    "wordLadder": [
      "fast",
      "bast",
      "best",
      "beat",
      "feat"
    ]
  },
  {
    "id": 125,
    "beginWord": "fort",
    "endWord": "gate",
    "wordLadder": [
      "sort",
      "sore",
      "some",
      "same",
      "game"
    ]
  },
  {
    "id": 126,
    "beginWord": "gain",
    "endWord": "gone",
    "wordLadder": [
      "lain",
      "laid",
      "land",
      "lane",
      "lone"
    ]
  },
  {
    "id": 127,
    "beginWord": "gave",
    "endWord": "gene",
    "wordLadder": [
      "give",
      "live",
      "love",
      "lone",
      "gone"
    ]
  },
  {
    "id": 128,
    "beginWord": "goat",
    "endWord": "hall",
    "wordLadder": [
      "boat",
      "beat",
      "belt",
      "bell",
      "ball"
    ]
  },
  {
    "id": 129,
    "beginWord": "have",
    "endWord": "held",
    "wordLadder": [
      "save",
      "sale",
      "sole",
      "hole",
      "hold"
    ]
  },
  {
    "id": 130,
    "beginWord": "hear",
    "endWord": "hill",
    "wordLadder": [
      "bear",
      "beat",
      "belt",
      "bell",
      "bill"
    ]
  },
  {
    "id": 131,
    "beginWord": "hero",
    "endWord": "home",
    "wordLadder": [
      "here",
      "mere",
      "more",
      "core",
      "come"
    ]
  },
  {
    "id": 132,
    "beginWord": "host",
    "endWord": "jack",
    "wordLadder": [
      "post",
      "past",
      "part",
      "park",
      "pack"
    ]
  },
  {
    "id": 133,
    "beginWord": "hour",
    "endWord": "look",
    "wordLadder": [
      "pour",
      "poor",
      "pool",
      "cool",
      "cook"
    ]
  },
  {
    "id": 134,
    "beginWord": "john",
    "endWord": "load",
    "wordLadder": [
      "join",
      "coin",
      "corn",
      "cord",
      "lord"
    ]
  },
  {
    "id": 135,
    "beginWord": "join",
    "endWord": "jury",
    "wordLadder": [
      "coin",
      "corn",
      "born",
      "burn",
      "bury"
    ]
  },
  {
    "id": 136,
    "beginWord": "just",
    "endWord": "lake",
    "wordLadder": [
      "must",
      "mast",
      "cast",
      "case",
      "cake"
    ]
  },
  {
    "id": 137,
    "beginWord": "soft",
    "endWord": "hard",
    "wordLadder": [
      "sort",
      "fort",
      "ford",
      "cord",
      "card"
    ]
  },
  {
    "id": 138,
    "beginWord": "slow",
    "endWord": "fast",
    "wordLadder": [
      "flow",
      "flaw",
      "flat",
      "feat",
      "beat",
      "best",
      "bast"
    ]
  },
  {
    "id": 139,
    "beginWord": "four",
    "endWord": "five",
    "wordLadder": [
      "pour",
      "poor",
      "pool",
      "tool",
      "toll",
      "roll",
      "role",
      "rile",
      "file"
    ]
  },
  {
    "id": 140,
    "beginWord": "game",
    "endWord": "play",
    "wordLadder": [
      "came",
      "case",
      "base",
      "bast",
      "best",
      "beat",
      "feat",
      "flat",
      "flay"
    ]
  }
],
  fr: [
  {
    "id": 1,
    "beginWord": "alu",
    "endWord": "emu",
    "wordLadder": [
      "elu"
    ]
  },
  {
    "id": 2,
    "beginWord": "ble",
    "endWord": "ils",
    "wordLadder": [
      "ile"
    ]
  },
  {
    "id": 3,
    "beginWord": "aleas",
    "endWord": "arias",
    "wordLadder": [
      "alias"
    ]
  },
  {
    "id": 4,
    "beginWord": "bidon",
    "endWord": "bisou",
    "wordLadder": [
      "bison"
    ]
  },
  {
    "id": 5,
    "beginWord": "blanc",
    "endWord": "franc",
    "wordLadder": [
      "flanc"
    ]
  },
  {
    "id": 6,
    "beginWord": "cieux",
    "endWord": "voeux",
    "wordLadder": [
      "vieux"
    ]
  },
  {
    "id": 7,
    "beginWord": "epais",
    "endWord": "etats",
    "wordLadder": [
      "etais"
    ]
  },
  {
    "id": 8,
    "beginWord": "fatal",
    "endWord": "naval",
    "wordLadder": [
      "natal"
    ]
  },
  {
    "id": 9,
    "beginWord": "geant",
    "endWord": "niant",
    "wordLadder": [
      "neant"
    ]
  },
  {
    "id": 10,
    "beginWord": "jadis",
    "endWord": "ravis",
    "wordLadder": [
      "radis"
    ]
  },
  {
    "id": 11,
    "beginWord": "japon",
    "endWord": "juron",
    "wordLadder": [
      "jupon"
    ]
  },
  {
    "id": 12,
    "beginWord": "legal",
    "endWord": "metal",
    "wordLadder": [
      "letal"
    ]
  },
  {
    "id": 13,
    "beginWord": "nerfs",
    "endWord": "oeufs",
    "wordLadder": [
      "neufs"
    ]
  },
  {
    "id": 14,
    "beginWord": "raide",
    "endWord": "rails",
    "wordLadder": [
      "raids"
    ]
  },
  {
    "id": 15,
    "beginWord": "score",
    "endWord": "sport",
    "wordLadder": [
      "spore"
    ]
  },
  {
    "id": 16,
    "beginWord": "abimer",
    "endWord": "animes",
    "wordLadder": [
      "animer"
    ]
  },
  {
    "id": 17,
    "beginWord": "acides",
    "endWord": "avises",
    "wordLadder": [
      "avides"
    ]
  },
  {
    "id": 18,
    "beginWord": "acteur",
    "endWord": "autour",
    "wordLadder": [
      "auteur"
    ]
  },
  {
    "id": 19,
    "beginWord": "allais",
    "endWord": "allant",
    "wordLadder": [
      "allait"
    ]
  },
  {
    "id": 20,
    "beginWord": "amical",
    "endWord": "amoral",
    "wordLadder": [
      "amiral"
    ]
  },
  {
    "id": 21,
    "beginWord": "aprete",
    "endWord": "arrets",
    "wordLadder": [
      "arrete"
    ]
  },
  {
    "id": 22,
    "beginWord": "banque",
    "endWord": "vasque",
    "wordLadder": [
      "basque"
    ]
  },
  {
    "id": 23,
    "beginWord": "barons",
    "endWord": "tatons",
    "wordLadder": [
      "batons"
    ]
  },
  {
    "id": 24,
    "beginWord": "battre",
    "endWord": "battus",
    "wordLadder": [
      "battue"
    ]
  },
  {
    "id": 25,
    "beginWord": "belier",
    "endWord": "renier",
    "wordLadder": [
      "relier"
    ]
  },
  {
    "id": 26,
    "beginWord": "boiter",
    "endWord": "bottes",
    "wordLadder": [
      "boites"
    ]
  },
  {
    "id": 27,
    "beginWord": "boiton",
    "endWord": "mouton",
    "wordLadder": [
      "bouton"
    ]
  },
  {
    "id": 28,
    "beginWord": "bouffe",
    "endWord": "touffu",
    "wordLadder": [
      "touffe"
    ]
  },
  {
    "id": 29,
    "beginWord": "cagnes",
    "endWord": "pannes",
    "wordLadder": [
      "cannes"
    ]
  },
  {
    "id": 30,
    "beginWord": "chiper",
    "endWord": "choyer",
    "wordLadder": [
      "choper"
    ]
  },
  {
    "id": 31,
    "beginWord": "cingle",
    "endWord": "jungle",
    "wordLadder": [
      "jingle"
    ]
  },
  {
    "id": 32,
    "beginWord": "citees",
    "endWord": "dotees",
    "wordLadder": [
      "cotees"
    ]
  },
  {
    "id": 33,
    "beginWord": "dechet",
    "endWord": "secret",
    "wordLadder": [
      "decret"
    ]
  },
  {
    "id": 34,
    "beginWord": "decore",
    "endWord": "dehors",
    "wordLadder": [
      "decors"
    ]
  },
  {
    "id": 35,
    "beginWord": "dedire",
    "endWord": "retire",
    "wordLadder": [
      "redire"
    ]
  },
  {
    "id": 36,
    "beginWord": "defend",
    "endWord": "depens",
    "wordLadder": [
      "depend"
    ]
  },
  {
    "id": 37,
    "beginWord": "depart",
    "endWord": "report",
    "wordLadder": [
      "repart"
    ]
  },
  {
    "id": 38,
    "beginWord": "dessin",
    "endWord": "festin",
    "wordLadder": [
      "destin"
    ]
  },
  {
    "id": 39,
    "beginWord": "ecrire",
    "endWord": "ecrits",
    "wordLadder": [
      "ecrite"
    ]
  },
  {
    "id": 40,
    "beginWord": "egarer",
    "endWord": "etayer",
    "wordLadder": [
      "egayer"
    ]
  },
  {
    "id": 41,
    "beginWord": "espace",
    "endWord": "espere",
    "wordLadder": [
      "espece"
    ]
  },
  {
    "id": 42,
    "beginWord": "essaie",
    "endWord": "essuye",
    "wordLadder": [
      "essaye"
    ]
  },
  {
    "id": 43,
    "beginWord": "etable",
    "endWord": "stalle",
    "wordLadder": [
      "stable"
    ]
  },
  {
    "id": 44,
    "beginWord": "faites",
    "endWord": "suites",
    "wordLadder": [
      "fuites"
    ]
  },
  {
    "id": 45,
    "beginWord": "faudra",
    "endWord": "voudra",
    "wordLadder": [
      "vaudra"
    ]
  },
  {
    "id": 46,
    "beginWord": "ferons",
    "endWord": "seront",
    "wordLadder": [
      "serons"
    ]
  },
  {
    "id": 47,
    "beginWord": "fleuri",
    "endWord": "pleurs",
    "wordLadder": [
      "fleurs"
    ]
  },
  {
    "id": 48,
    "beginWord": "guelte",
    "endWord": "muette",
    "wordLadder": [
      "guette"
    ]
  },
  {
    "id": 49,
    "beginWord": "habile",
    "endWord": "habits",
    "wordLadder": [
      "habite"
    ]
  },
  {
    "id": 50,
    "beginWord": "hanche",
    "endWord": "marche",
    "wordLadder": [
      "manche"
    ]
  },
  {
    "id": 51,
    "beginWord": "inapte",
    "endWord": "inerte",
    "wordLadder": [
      "inepte"
    ]
  },
  {
    "id": 52,
    "beginWord": "infame",
    "endWord": "intime",
    "wordLadder": [
      "infime"
    ]
  },
  {
    "id": 53,
    "beginWord": "joints",
    "endWord": "pointu",
    "wordLadder": [
      "points"
    ]
  },
  {
    "id": 54,
    "beginWord": "jouait",
    "endWord": "jouent",
    "wordLadder": [
      "jouant"
    ]
  },
  {
    "id": 55,
    "beginWord": "libere",
    "endWord": "misere",
    "wordLadder": [
      "lisere"
    ]
  },
  {
    "id": 56,
    "beginWord": "maigre",
    "endWord": "naitre",
    "wordLadder": [
      "maitre"
    ]
  },
  {
    "id": 57,
    "beginWord": "mirage",
    "endWord": "visage",
    "wordLadder": [
      "virage"
    ]
  },
  {
    "id": 58,
    "beginWord": "parait",
    "endWord": "payant",
    "wordLadder": [
      "payait"
    ]
  },
  {
    "id": 59,
    "beginWord": "recule",
    "endWord": "refuse",
    "wordLadder": [
      "recuse"
    ]
  },
  {
    "id": 60,
    "beginWord": "reglee",
    "endWord": "regner",
    "wordLadder": [
      "regler"
    ]
  },
  {
    "id": 61,
    "beginWord": "sinuer",
    "endWord": "situes",
    "wordLadder": [
      "situer"
    ]
  },
  {
    "id": 62,
    "beginWord": "uriner",
    "endWord": "usines",
    "wordLadder": [
      "usiner"
    ]
  },
  {
    "id": 63,
    "beginWord": "abregee",
    "endWord": "abroger",
    "wordLadder": [
      "abreger"
    ]
  },
  {
    "id": 64,
    "beginWord": "absence",
    "endWord": "absents",
    "wordLadder": [
      "absente"
    ]
  },
  {
    "id": 65,
    "beginWord": "achetee",
    "endWord": "acheves",
    "wordLadder": [
      "achevee"
    ]
  },
  {
    "id": 66,
    "beginWord": "adaptee",
    "endWord": "adoptes",
    "wordLadder": [
      "adoptee"
    ]
  },
  {
    "id": 67,
    "beginWord": "affiler",
    "endWord": "enfiler",
    "wordLadder": [
      "effiler"
    ]
  },
  {
    "id": 68,
    "beginWord": "allegee",
    "endWord": "allegro",
    "wordLadder": [
      "allegre"
    ]
  },
  {
    "id": 69,
    "beginWord": "apposer",
    "endWord": "opposes",
    "wordLadder": [
      "opposer"
    ]
  },
  {
    "id": 70,
    "beginWord": "arrimer",
    "endWord": "arrives",
    "wordLadder": [
      "arriver"
    ]
  },
  {
    "id": 71,
    "beginWord": "assumer",
    "endWord": "assures",
    "wordLadder": [
      "assurer"
    ]
  },
  {
    "id": 72,
    "beginWord": "bagarre",
    "endWord": "bizarre",
    "wordLadder": [
      "bigarre"
    ]
  },
  {
    "id": 73,
    "beginWord": "baigner",
    "endWord": "soigner",
    "wordLadder": [
      "saigner"
    ]
  },
  {
    "id": 74,
    "beginWord": "berceau",
    "endWord": "cerveau",
    "wordLadder": [
      "cerceau"
    ]
  },
  {
    "id": 75,
    "beginWord": "bouchee",
    "endWord": "touches",
    "wordLadder": [
      "touchee"
    ]
  },
  {
    "id": 76,
    "beginWord": "caserne",
    "endWord": "taverne",
    "wordLadder": [
      "caverne"
    ]
  },
  {
    "id": 77,
    "beginWord": "cassant",
    "endWord": "passent",
    "wordLadder": [
      "passant"
    ]
  },
  {
    "id": 78,
    "beginWord": "cendres",
    "endWord": "rentres",
    "wordLadder": [
      "centres"
    ]
  },
  {
    "id": 79,
    "beginWord": "cessent",
    "endWord": "restent",
    "wordLadder": [
      "ressent"
    ]
  },
  {
    "id": 80,
    "beginWord": "confiee",
    "endWord": "convier",
    "wordLadder": [
      "confier"
    ]
  },
  {
    "id": 81,
    "beginWord": "costume",
    "endWord": "couture",
    "wordLadder": [
      "coutume"
    ]
  },
  {
    "id": 82,
    "beginWord": "coupees",
    "endWord": "souples",
    "wordLadder": [
      "couples"
    ]
  },
  {
    "id": 83,
    "beginWord": "decence",
    "endWord": "semence",
    "wordLadder": [
      "demence"
    ]
  },
  {
    "id": 84,
    "beginWord": "dechets",
    "endWord": "secrets",
    "wordLadder": [
      "decrets"
    ]
  },
  {
    "id": 85,
    "beginWord": "deposee",
    "endWord": "reposer",
    "wordLadder": [
      "deposer"
    ]
  },
  {
    "id": 86,
    "beginWord": "dessine",
    "endWord": "destins",
    "wordLadder": [
      "destine"
    ]
  },
  {
    "id": 87,
    "beginWord": "detient",
    "endWord": "revient",
    "wordLadder": [
      "retient"
    ]
  },
  {
    "id": 88,
    "beginWord": "domaine",
    "endWord": "romains",
    "wordLadder": [
      "romaine"
    ]
  },
  {
    "id": 89,
    "beginWord": "doublee",
    "endWord": "roubles",
    "wordLadder": [
      "doubles"
    ]
  },
  {
    "id": 90,
    "beginWord": "draguer",
    "endWord": "drogues",
    "wordLadder": [
      "droguer"
    ]
  },
  {
    "id": 91,
    "beginWord": "dressee",
    "endWord": "tresser",
    "wordLadder": [
      "dresser"
    ]
  },
  {
    "id": 92,
    "beginWord": "envolee",
    "endWord": "envoyes",
    "wordLadder": [
      "envoyee"
    ]
  },
  {
    "id": 93,
    "beginWord": "espacer",
    "endWord": "especes",
    "wordLadder": [
      "espaces"
    ]
  },
  {
    "id": 94,
    "beginWord": "fermees",
    "endWord": "formels",
    "wordLadder": [
      "formees"
    ]
  },
  {
    "id": 95,
    "beginWord": "figuier",
    "endWord": "figures",
    "wordLadder": [
      "figurer"
    ]
  },
  {
    "id": 96,
    "beginWord": "fournee",
    "endWord": "tournes",
    "wordLadder": [
      "tournee"
    ]
  },
  {
    "id": 97,
    "beginWord": "gagnait",
    "endWord": "gagnent",
    "wordLadder": [
      "gagnant"
    ]
  },
  {
    "id": 98,
    "beginWord": "gardait",
    "endWord": "gardent",
    "wordLadder": [
      "gardant"
    ]
  },
  {
    "id": 99,
    "beginWord": "glacier",
    "endWord": "gravier",
    "wordLadder": [
      "gracier"
    ]
  },
  {
    "id": 100,
    "beginWord": "greffer",
    "endWord": "griffes",
    "wordLadder": [
      "greffes"
    ]
  },
  {
    "id": 101,
    "beginWord": "haillon",
    "endWord": "maillot",
    "wordLadder": [
      "maillon"
    ]
  },
  {
    "id": 102,
    "beginWord": "haineux",
    "endWord": "laiteux",
    "wordLadder": [
      "laineux"
    ]
  },
  {
    "id": 103,
    "beginWord": "inciter",
    "endWord": "invites",
    "wordLadder": [
      "inviter"
    ]
  },
  {
    "id": 104,
    "beginWord": "inculpe",
    "endWord": "insulte",
    "wordLadder": [
      "inculte"
    ]
  },
  {
    "id": 105,
    "beginWord": "langues",
    "endWord": "longuet",
    "wordLadder": [
      "longues"
    ]
  },
  {
    "id": 106,
    "beginWord": "laniere",
    "endWord": "miniere",
    "wordLadder": [
      "maniere"
    ]
  },
  {
    "id": 107,
    "beginWord": "manager",
    "endWord": "menages",
    "wordLadder": [
      "menager"
    ]
  },
  {
    "id": 108,
    "beginWord": "nourrie",
    "endWord": "pourrir",
    "wordLadder": [
      "nourrir"
    ]
  },
  {
    "id": 109,
    "beginWord": "offrait",
    "endWord": "offrent",
    "wordLadder": [
      "offrant"
    ]
  },
  {
    "id": 110,
    "beginWord": "oubliee",
    "endWord": "publies",
    "wordLadder": [
      "publiee"
    ]
  },
  {
    "id": 111,
    "beginWord": "ouvrait",
    "endWord": "ouvrent",
    "wordLadder": [
      "ouvrant"
    ]
  },
  {
    "id": 112,
    "beginWord": "paginer",
    "endWord": "potiner",
    "wordLadder": [
      "patiner"
    ]
  },
  {
    "id": 113,
    "beginWord": "peloter",
    "endWord": "pilotes",
    "wordLadder": [
      "piloter"
    ]
  },
  {
    "id": 114,
    "beginWord": "pendant",
    "endWord": "vendent",
    "wordLadder": [
      "vendant"
    ]
  },
  {
    "id": 115,
    "beginWord": "pouvais",
    "endWord": "pouvant",
    "wordLadder": [
      "pouvait"
    ]
  },
  {
    "id": 116,
    "beginWord": "prenait",
    "endWord": "pronant",
    "wordLadder": [
      "prenant"
    ]
  },
  {
    "id": 117,
    "beginWord": "probite",
    "endWord": "profits",
    "wordLadder": [
      "profite"
    ]
  },
  {
    "id": 118,
    "beginWord": "radiner",
    "endWord": "raviver",
    "wordLadder": [
      "raviner"
    ]
  },
  {
    "id": 119,
    "beginWord": "recours",
    "endWord": "sejours",
    "wordLadder": [
      "secours"
    ]
  },
  {
    "id": 120,
    "beginWord": "regarde",
    "endWord": "retards",
    "wordLadder": [
      "retarde"
    ]
  },
  {
    "id": 121,
    "beginWord": "reussie",
    "endWord": "roussir",
    "wordLadder": [
      "reussir"
    ]
  },
  {
    "id": 122,
    "beginWord": "sorcier",
    "endWord": "soulier",
    "wordLadder": [
      "soucier"
    ]
  },
  {
    "id": 123,
    "beginWord": "suffira",
    "endWord": "suffixe",
    "wordLadder": [
      "suffire"
    ]
  },
  {
    "id": 124,
    "beginWord": "suivait",
    "endWord": "suivent",
    "wordLadder": [
      "suivant"
    ]
  },
  {
    "id": 125,
    "beginWord": "tombait",
    "endWord": "tombent",
    "wordLadder": [
      "tombant"
    ]
  },
  {
    "id": 126,
    "beginWord": "trainee",
    "endWord": "traitre",
    "wordLadder": [
      "traitee"
    ]
  },
  {
    "id": 127,
    "beginWord": "urgence",
    "endWord": "urgents",
    "wordLadder": [
      "urgente"
    ]
  },
  {
    "id": 128,
    "beginWord": "accusait",
    "endWord": "accusent",
    "wordLadder": [
      "accusant"
    ]
  },
  {
    "id": 129,
    "beginWord": "ajoutait",
    "endWord": "ajoutent",
    "wordLadder": [
      "ajoutant"
    ]
  },
  {
    "id": 130,
    "beginWord": "arrivait",
    "endWord": "arrivent",
    "wordLadder": [
      "arrivant"
    ]
  },
  {
    "id": 131,
    "beginWord": "assurait",
    "endWord": "assurent",
    "wordLadder": [
      "assurant"
    ]
  },
  {
    "id": 132,
    "beginWord": "attendre",
    "endWord": "attendus",
    "wordLadder": [
      "attendue"
    ]
  },
  {
    "id": 133,
    "beginWord": "ceinture",
    "endWord": "pointure",
    "wordLadder": [
      "peinture"
    ]
  },
  {
    "id": 134,
    "beginWord": "centaine",
    "endWord": "certains",
    "wordLadder": [
      "certaine"
    ]
  },
  {
    "id": 135,
    "beginWord": "citation",
    "endWord": "rotation",
    "wordLadder": [
      "cotation"
    ]
  },
  {
    "id": 136,
    "beginWord": "comptait",
    "endWord": "comptent",
    "wordLadder": [
      "comptant"
    ]
  },
  {
    "id": 137,
    "beginWord": "confirme",
    "endWord": "conforte",
    "wordLadder": [
      "conforme"
    ]
  },
  {
    "id": 138,
    "beginWord": "couchant",
    "endWord": "touchent",
    "wordLadder": [
      "touchant"
    ]
  },
  {
    "id": 139,
    "beginWord": "decidait",
    "endWord": "decident",
    "wordLadder": [
      "decidant"
    ]
  },
  {
    "id": 140,
    "beginWord": "defoncer",
    "endWord": "renoncer",
    "wordLadder": [
      "denoncer"
    ]
  },
  {
    "id": 141,
    "beginWord": "deformer",
    "endWord": "reformes",
    "wordLadder": [
      "reformer"
    ]
  },
  {
    "id": 142,
    "beginWord": "degriser",
    "endWord": "deguises",
    "wordLadder": [
      "deguiser"
    ]
  },
  {
    "id": 143,
    "beginWord": "delecter",
    "endWord": "detester",
    "wordLadder": [
      "detecter"
    ]
  },
  {
    "id": 144,
    "beginWord": "delirant",
    "endWord": "desirent",
    "wordLadder": [
      "desirant"
    ]
  },
  {
    "id": 145,
    "beginWord": "departir",
    "endWord": "repartis",
    "wordLadder": [
      "repartir"
    ]
  },
  {
    "id": 146,
    "beginWord": "deplacee",
    "endWord": "replacer",
    "wordLadder": [
      "deplacer"
    ]
  },
  {
    "id": 147,
    "beginWord": "deportee",
    "endWord": "reporter",
    "wordLadder": [
      "reportee"
    ]
  },
  {
    "id": 148,
    "beginWord": "designee",
    "endWord": "resigner",
    "wordLadder": [
      "designer"
    ]
  },
  {
    "id": 149,
    "beginWord": "dessinee",
    "endWord": "destines",
    "wordLadder": [
      "destinee"
    ]
  },
  {
    "id": 150,
    "beginWord": "detruire",
    "endWord": "detruits",
    "wordLadder": [
      "detruite"
    ]
  },
  {
    "id": 151,
    "beginWord": "discutee",
    "endWord": "disputer",
    "wordLadder": [
      "disputee"
    ]
  },
  {
    "id": 152,
    "beginWord": "emporter",
    "endWord": "importes",
    "wordLadder": [
      "importer"
    ]
  },
  {
    "id": 153,
    "beginWord": "estimait",
    "endWord": "estiment",
    "wordLadder": [
      "estimant"
    ]
  },
  {
    "id": 154,
    "beginWord": "evaluent",
    "endWord": "evoquent",
    "wordLadder": [
      "evoluent"
    ]
  },
  {
    "id": 155,
    "beginWord": "existait",
    "endWord": "existent",
    "wordLadder": [
      "existant"
    ]
  },
  {
    "id": 156,
    "beginWord": "faudrait",
    "endWord": "voudrait",
    "wordLadder": [
      "vaudrait"
    ]
  },
  {
    "id": 157,
    "beginWord": "ignorait",
    "endWord": "ignorent",
    "wordLadder": [
      "ignorant"
    ]
  },
  {
    "id": 158,
    "beginWord": "inscrire",
    "endWord": "inscrits",
    "wordLadder": [
      "inscrite"
    ]
  },
  {
    "id": 159,
    "beginWord": "jaquette",
    "endWord": "roquette",
    "wordLadder": [
      "raquette"
    ]
  },
  {
    "id": 160,
    "beginWord": "materiel",
    "endWord": "paternel",
    "wordLadder": [
      "maternel"
    ]
  },
  {
    "id": 161,
    "beginWord": "montrait",
    "endWord": "montrent",
    "wordLadder": [
      "montrant"
    ]
  },
  {
    "id": 162,
    "beginWord": "occupait",
    "endWord": "occupent",
    "wordLadder": [
      "occupant"
    ]
  },
  {
    "id": 163,
    "beginWord": "opposait",
    "endWord": "opposent",
    "wordLadder": [
      "opposant"
    ]
  },
  {
    "id": 164,
    "beginWord": "original",
    "endWord": "origines",
    "wordLadder": [
      "originel"
    ]
  },
  {
    "id": 165,
    "beginWord": "oubliant",
    "endWord": "publient",
    "wordLadder": [
      "publiant"
    ]
  },
  {
    "id": 166,
    "beginWord": "paisible",
    "endWord": "possible",
    "wordLadder": [
      "passible"
    ]
  },
  {
    "id": 167,
    "beginWord": "passager",
    "endWord": "paysages",
    "wordLadder": [
      "passages"
    ]
  },
  {
    "id": 168,
    "beginWord": "patience",
    "endWord": "patients",
    "wordLadder": [
      "patiente"
    ]
  },
  {
    "id": 169,
    "beginWord": "preferee",
    "endWord": "proferer",
    "wordLadder": [
      "preferer"
    ]
  },
  {
    "id": 170,
    "beginWord": "preposer",
    "endWord": "proposes",
    "wordLadder": [
      "proposer"
    ]
  },
  {
    "id": 171,
    "beginWord": "presence",
    "endWord": "presents",
    "wordLadder": [
      "presente"
    ]
  },
  {
    "id": 172,
    "beginWord": "prudence",
    "endWord": "prudents",
    "wordLadder": [
      "prudente"
    ]
  },
  {
    "id": 173,
    "beginWord": "quittait",
    "endWord": "quittent",
    "wordLadder": [
      "quittant"
    ]
  },
  {
    "id": 174,
    "beginWord": "realisee",
    "endWord": "realites",
    "wordLadder": [
      "realises"
    ]
  },
  {
    "id": 175,
    "beginWord": "recolter",
    "endWord": "revolver",
    "wordLadder": [
      "revolter"
    ]
  },
  {
    "id": 176,
    "beginWord": "refusait",
    "endWord": "refusent",
    "wordLadder": [
      "refusant"
    ]
  },
  {
    "id": 177,
    "beginWord": "remarque",
    "endWord": "retorque",
    "wordLadder": [
      "remorque"
    ]
  },
  {
    "id": 178,
    "beginWord": "semblait",
    "endWord": "semblent",
    "wordLadder": [
      "semblant"
    ]
  },
  {
    "id": 179,
    "beginWord": "soutiens",
    "endWord": "souvient",
    "wordLadder": [
      "souviens"
    ]
  },
  {
    "id": 180,
    "beginWord": "violence",
    "endWord": "violents",
    "wordLadder": [
      "violente"
    ]
  },
  {
    "id": 181,
    "beginWord": "anche",
    "endWord": "entre",
    "wordLadder": [
      "ancre",
      "encre"
    ]
  },
  {
    "id": 182,
    "beginWord": "astre",
    "endWord": "ouvre",
    "wordLadder": [
      "autre",
      "outre"
    ]
  },
  {
    "id": 183,
    "beginWord": "benin",
    "endWord": "vetir",
    "wordLadder": [
      "venin",
      "venir"
    ]
  },
  {
    "id": 184,
    "beginWord": "bocal",
    "endWord": "royal",
    "wordLadder": [
      "local",
      "loyal"
    ]
  },
  {
    "id": 185,
    "beginWord": "chope",
    "endWord": "glose",
    "wordLadder": [
      "clope",
      "close"
    ]
  },
  {
    "id": 186,
    "beginWord": "coeur",
    "endWord": "tueur",
    "wordLadder": [
      "soeur",
      "sueur"
    ]
  },
  {
    "id": 187,
    "beginWord": "allees",
    "endWord": "altier",
    "wordLadder": [
      "allies",
      "allier"
    ]
  },
  {
    "id": 188,
    "beginWord": "amande",
    "endWord": "amenes",
    "wordLadder": [
      "amende",
      "amenee"
    ]
  },
  {
    "id": 189,
    "beginWord": "baisse",
    "endWord": "suisse",
    "wordLadder": [
      "caisse",
      "cuisse"
    ]
  },
  {
    "id": 190,
    "beginWord": "bateau",
    "endWord": "rideau",
    "wordLadder": [
      "rateau",
      "radeau"
    ]
  },
  {
    "id": 191,
    "beginWord": "chiant",
    "endWord": "orient",
    "wordLadder": [
      "criant",
      "crient"
    ]
  },
  {
    "id": 192,
    "beginWord": "concis",
    "endWord": "connut",
    "wordLadder": [
      "concus",
      "connus"
    ]
  },
  {
    "id": 193,
    "beginWord": "epicer",
    "endWord": "exiles",
    "wordLadder": [
      "epiler",
      "exiler"
    ]
  },
  {
    "id": 194,
    "beginWord": "faible",
    "endWord": "veille",
    "wordLadder": [
      "faille",
      "vaille"
    ]
  },
  {
    "id": 195,
    "beginWord": "glande",
    "endWord": "orange",
    "wordLadder": [
      "grande",
      "grange"
    ]
  },
  {
    "id": 196,
    "beginWord": "gradin",
    "endWord": "gratos",
    "wordLadder": [
      "gratin",
      "gratis"
    ]
  },
  {
    "id": 197,
    "beginWord": "motion",
    "endWord": "ration",
    "wordLadder": [
      "notion",
      "nation"
    ]
  },
  {
    "id": 198,
    "beginWord": "notait",
    "endWord": "voyant",
    "wordLadder": [
      "notant",
      "votant"
    ]
  },
  {
    "id": 199,
    "beginWord": "oignon",
    "endWord": "rognon",
    "wordLadder": [
      "pignon",
      "pognon"
    ]
  },
  {
    "id": 200,
    "beginWord": "pesait",
    "endWord": "posent",
    "wordLadder": [
      "posait",
      "posant"
    ]
  },
  {
    "id": 201,
    "beginWord": "savais",
    "endWord": "savent",
    "wordLadder": [
      "savait",
      "savant"
    ]
  },
  {
    "id": 202,
    "beginWord": "bailler",
    "endWord": "taillis",
    "wordLadder": [
      "tailler",
      "tailles"
    ]
  },
  {
    "id": 203,
    "beginWord": "blanche",
    "endWord": "tronche",
    "wordLadder": [
      "branche",
      "tranche"
    ]
  },
  {
    "id": 204,
    "beginWord": "bourges",
    "endWord": "courtes",
    "wordLadder": [
      "bourses",
      "courses"
    ]
  },
  {
    "id": 205,
    "beginWord": "chasser",
    "endWord": "clauses",
    "wordLadder": [
      "classer",
      "classes"
    ]
  },
  {
    "id": 206,
    "beginWord": "comites",
    "endWord": "dompter",
    "wordLadder": [
      "comptes",
      "compter"
    ]
  },
  {
    "id": 207,
    "beginWord": "content",
    "endWord": "souvent",
    "wordLadder": [
      "coutent",
      "couvent"
    ]
  },
  {
    "id": 208,
    "beginWord": "decolle",
    "endWord": "deroute",
    "wordLadder": [
      "decoule",
      "deroule"
    ]
  },
  {
    "id": 209,
    "beginWord": "detenir",
    "endWord": "revetir",
    "wordLadder": [
      "retenir",
      "revenir"
    ]
  },
  {
    "id": 210,
    "beginWord": "ecoulee",
    "endWord": "ecoutes",
    "wordLadder": [
      "ecouler",
      "ecouter"
    ]
  },
  {
    "id": 211,
    "beginWord": "empaler",
    "endWord": "expirer",
    "wordLadder": [
      "empiler",
      "empirer"
    ]
  },
  {
    "id": 212,
    "beginWord": "grouper",
    "endWord": "trouves",
    "wordLadder": [
      "groupes",
      "troupes"
    ]
  },
  {
    "id": 213,
    "beginWord": "heriter",
    "endWord": "verites",
    "wordLadder": [
      "meriter",
      "merites"
    ]
  },
  {
    "id": 214,
    "beginWord": "martial",
    "endWord": "parties",
    "wordLadder": [
      "partial",
      "partiel"
    ]
  },
  {
    "id": 215,
    "beginWord": "modeler",
    "endWord": "moderne",
    "wordLadder": [
      "moderer",
      "moderee"
    ]
  },
  {
    "id": 216,
    "beginWord": "ravager",
    "endWord": "rivales",
    "wordLadder": [
      "ravages",
      "rivages"
    ]
  },
  {
    "id": 217,
    "beginWord": "blanches",
    "endWord": "tranchet",
    "wordLadder": [
      "branches",
      "tranches"
    ]
  },
  {
    "id": 218,
    "beginWord": "boursier",
    "endWord": "fourrier",
    "wordLadder": [
      "coursier",
      "courrier"
    ]
  },
  {
    "id": 219,
    "beginWord": "conduira",
    "endWord": "conduits",
    "wordLadder": [
      "conduire",
      "conduite"
    ]
  },
  {
    "id": 220,
    "beginWord": "contente",
    "endWord": "convenus",
    "wordLadder": [
      "contenue",
      "contenus"
    ]
  },
  {
    "id": 221,
    "beginWord": "debander",
    "endWord": "deranger",
    "wordLadder": [
      "demander",
      "demanger"
    ]
  },
  {
    "id": 222,
    "beginWord": "decoller",
    "endWord": "deroules",
    "wordLadder": [
      "decouler",
      "derouler"
    ]
  },
  {
    "id": 223,
    "beginWord": "defenses",
    "endWord": "repenser",
    "wordLadder": [
      "depenses",
      "depenser"
    ]
  },
  {
    "id": 224,
    "beginWord": "deflorer",
    "endWord": "deployes",
    "wordLadder": [
      "deplorer",
      "deployer"
    ]
  },
  {
    "id": 225,
    "beginWord": "depassee",
    "endWord": "revasser",
    "wordLadder": [
      "depasser",
      "repasser"
    ]
  },
  {
    "id": 226,
    "beginWord": "deprimer",
    "endWord": "reprises",
    "wordLadder": [
      "reprimer",
      "repriser"
    ]
  },
  {
    "id": 227,
    "beginWord": "detenait",
    "endWord": "revenant",
    "wordLadder": [
      "devenait",
      "revenait"
    ]
  },
  {
    "id": 228,
    "beginWord": "ecrivain",
    "endWord": "ecrivent",
    "wordLadder": [
      "ecrivait",
      "ecrivant"
    ]
  },
  {
    "id": 229,
    "beginWord": "engendre",
    "endWord": "entendus",
    "wordLadder": [
      "entendre",
      "entendue"
    ]
  },
  {
    "id": 230,
    "beginWord": "feuilles",
    "endWord": "souiller",
    "wordLadder": [
      "fouilles",
      "fouiller"
    ]
  },
  {
    "id": 231,
    "beginWord": "imposait",
    "endWord": "impotent",
    "wordLadder": [
      "imposant",
      "imposent"
    ]
  },
  {
    "id": 232,
    "beginWord": "laissait",
    "endWord": "naissent",
    "wordLadder": [
      "laissant",
      "laissent"
    ]
  },
  {
    "id": 233,
    "beginWord": "manquait",
    "endWord": "marquent",
    "wordLadder": [
      "marquait",
      "marquant"
    ]
  },
  {
    "id": 234,
    "beginWord": "precedee",
    "endWord": "procedes",
    "wordLadder": [
      "preceder",
      "proceder"
    ]
  },
  {
    "id": 235,
    "beginWord": "produira",
    "endWord": "produits",
    "wordLadder": [
      "produire",
      "produite"
    ]
  },
  {
    "id": 236,
    "beginWord": "traduira",
    "endWord": "traduits",
    "wordLadder": [
      "traduire",
      "traduite"
    ]
  },
  {
    "id": 237,
    "beginWord": "agile",
    "endWord": "evite",
    "wordLadder": [
      "agite",
      "alite",
      "elite"
    ]
  },
  {
    "id": 238,
    "beginWord": "arabe",
    "endWord": "vrais",
    "wordLadder": [
      "crabe",
      "craie",
      "vraie"
    ]
  },
  {
    "id": 239,
    "beginWord": "chaos",
    "endWord": "clefs",
    "wordLadder": [
      "chars",
      "chers",
      "chefs"
    ]
  },
  {
    "id": 240,
    "beginWord": "aidant",
    "endWord": "urgent",
    "wordLadder": [
      "aident",
      "ardent",
      "argent"
    ]
  },
  {
    "id": 241,
    "beginWord": "baiser",
    "endWord": "trimer",
    "wordLadder": [
      "briser",
      "friser",
      "frimer"
    ]
  },
  {
    "id": 242,
    "beginWord": "beurre",
    "endWord": "tourne",
    "wordLadder": [
      "bourre",
      "bourbe",
      "tourbe"
    ]
  },
  {
    "id": 243,
    "beginWord": "crotte",
    "endWord": "trouve",
    "wordLadder": [
      "croute",
      "croupe",
      "troupe"
    ]
  },
  {
    "id": 244,
    "beginWord": "cuivre",
    "endWord": "survit",
    "wordLadder": [
      "suivre",
      "suivie",
      "survie"
    ]
  },
  {
    "id": 245,
    "beginWord": "pacage",
    "endWord": "rivale",
    "wordLadder": [
      "pavage",
      "ravage",
      "rivage"
    ]
  },
  {
    "id": 246,
    "beginWord": "braquer",
    "endWord": "truquer",
    "wordLadder": [
      "craquer",
      "croquer",
      "troquer"
    ]
  },
  {
    "id": 247,
    "beginWord": "connais",
    "endWord": "donnent",
    "wordLadder": [
      "connait",
      "donnait",
      "donnant"
    ]
  },
  {
    "id": 248,
    "beginWord": "commence",
    "endWord": "pompette",
    "wordLadder": [
      "commente",
      "commette",
      "pommette"
    ]
  },
  {
    "id": 249,
    "beginWord": "decelant",
    "endWord": "relevent",
    "wordLadder": [
      "decevant",
      "recevant",
      "relevant"
    ]
  },
  {
    "id": 250,
    "beginWord": "becher",
    "endWord": "vaches",
    "wordLadder": [
      "lecher",
      "lacher",
      "cacher",
      "caches"
    ]
  },
  {
    "id": 251,
    "beginWord": "bloque",
    "endWord": "truque",
    "wordLadder": [
      "cloque",
      "claque",
      "craque",
      "traque"
    ]
  },
  {
    "id": 252,
    "beginWord": "minces",
    "endWord": "singes",
    "wordLadder": [
      "pinces",
      "pieces",
      "pieges",
      "sieges"
    ]
  },
  {
    "id": 253,
    "beginWord": "baisser",
    "endWord": "suisses",
    "wordLadder": [
      "laisser",
      "laisses",
      "caisses",
      "cuisses"
    ]
  },
  {
    "id": 254,
    "beginWord": "decorer",
    "endWord": "renover",
    "wordLadder": [
      "devorer",
      "devouer",
      "denouer",
      "renouer"
    ]
  },
  {
    "id": 255,
    "beginWord": "dormant",
    "endWord": "servent",
    "wordLadder": [
      "dorment",
      "forment",
      "ferment",
      "serment"
    ]
  },
  {
    "id": 256,
    "beginWord": "aber",
    "endWord": "unit",
    "wordLadder": [
      "amer",
      "ames",
      "amis",
      "anis",
      "unis"
    ]
  },
  {
    "id": 257,
    "beginWord": "cabale",
    "endWord": "solive",
    "wordLadder": [
      "cabane",
      "cabine",
      "sabine",
      "saline",
      "salive"
    ]
  },
  {
    "id": 258,
    "beginWord": "fausser",
    "endWord": "tousser",
    "wordLadder": [
      "hausser",
      "hausses",
      "housses",
      "pousses",
      "pousser"
    ]
  },
  {
    "id": 259,
    "beginWord": "parfait",
    "endWord": "sortent",
    "wordLadder": [
      "parlait",
      "parlant",
      "partant",
      "portant",
      "sortant"
    ]
  },
  {
    "id": 260,
    "beginWord": "blair",
    "endWord": "trous",
    "wordLadder": [
      "clair",
      "chair",
      "choir",
      "choix",
      "croix",
      "crois",
      "trois"
    ]
  },
  {
    "id": 261,
    "beginWord": "debats",
    "endWord": "severe",
    "wordLadder": [
      "debuts",
      "debute",
      "depute",
      "repute",
      "repete",
      "repere",
      "revere"
    ]
  }
],
}
