/**
 * Countries and continents aligned with marcel-games-backend (3-letter ISO codes).
 * codeAlpha2 is used for Mapbox layers (iso_3166_1_alpha_2).
 */
export type Continent =
  | "AFRICA"
  | "ASIA"
  | "EUROPE"
  | "AMERICAS"
  | "OCEANIA"
  | "ANTARCTICA"

export type CountryLocale = "en" | "fr"

export interface Country {
  nameEn: string
  nameFr: string
  code: string
  codeAlpha2: string
  continent: Continent
}

/** Returns the country name in the given locale. */
export function getCountryName(country: Country, locale: CountryLocale): string {
  return locale === "fr" ? country.nameFr : country.nameEn
}

export const countries: Country[] = [
  { nameEn: "Afghanistan", nameFr: "Afghanistan", code: "AFG", codeAlpha2: "AF", continent: "ASIA" },
  { nameEn: "Angola", nameFr: "Angola", code: "AGO", codeAlpha2: "AO", continent: "AFRICA" },
  { nameEn: "Albania", nameFr: "Albanie", code: "ALB", codeAlpha2: "AL", continent: "EUROPE" },
  { nameEn: "United Arab Emirates", nameFr: "\u00c9mirats arabes unis", code: "ARE", codeAlpha2: "AE", continent: "ASIA" },
  { nameEn: "Argentina", nameFr: "Argentine", code: "ARG", codeAlpha2: "AR", continent: "AMERICAS" },
  { nameEn: "Armenia", nameFr: "Arm\u00e9nie", code: "ARM", codeAlpha2: "AM", continent: "ASIA" },
  { nameEn: "Antarctica", nameFr: "Antarctique", code: "ATA", codeAlpha2: "AQ", continent: "ANTARCTICA" },
  { nameEn: "Australia", nameFr: "Australie", code: "AUS", codeAlpha2: "AU", continent: "OCEANIA" },
  { nameEn: "Austria", nameFr: "Autriche", code: "AUT", codeAlpha2: "AT", continent: "EUROPE" },
  { nameEn: "Azerbaijan", nameFr: "Azerba\u00efdjan", code: "AZE", codeAlpha2: "AZ", continent: "ASIA" },
  { nameEn: "Burundi", nameFr: "Burundi", code: "BDI", codeAlpha2: "BI", continent: "AFRICA" },
  { nameEn: "Belgium", nameFr: "Belgique", code: "BEL", codeAlpha2: "BE", continent: "EUROPE" },
  { nameEn: "Benin", nameFr: "B\u00e9nin", code: "BEN", codeAlpha2: "BJ", continent: "AFRICA" },
  { nameEn: "Burkina Faso", nameFr: "Burkina Faso", code: "BFA", codeAlpha2: "BF", continent: "AFRICA" },
  { nameEn: "Bangladesh", nameFr: "Bangladesh", code: "BGD", codeAlpha2: "BD", continent: "ASIA" },
  { nameEn: "Bulgaria", nameFr: "Bulgarie", code: "BGR", codeAlpha2: "BG", continent: "EUROPE" },
  { nameEn: "Bahamas", nameFr: "Bahamas", code: "BHS", codeAlpha2: "BS", continent: "AMERICAS" },
  { nameEn: "Bosnia and Herzegovina", nameFr: "Bosnie-Herz\u00e9govine", code: "BIH", codeAlpha2: "BA", continent: "EUROPE" },
  { nameEn: "Belarus", nameFr: "Bi\u00e9lorussie", code: "BLR", codeAlpha2: "BY", continent: "EUROPE" },
  { nameEn: "Belize", nameFr: "Belize", code: "BLZ", codeAlpha2: "BZ", continent: "AMERICAS" },
  { nameEn: "Bolivia", nameFr: "Bolivie", code: "BOL", codeAlpha2: "BO", continent: "AMERICAS" },
  { nameEn: "Brazil", nameFr: "Br\u00e9sil", code: "BRA", codeAlpha2: "BR", continent: "AMERICAS" },
  { nameEn: "Brunei", nameFr: "Brunei", code: "BRN", codeAlpha2: "BN", continent: "ASIA" },
  { nameEn: "Bhutan", nameFr: "Bhoutan", code: "BTN", codeAlpha2: "BT", continent: "ASIA" },
  { nameEn: "Botswana", nameFr: "Botswana", code: "BWA", codeAlpha2: "BW", continent: "AFRICA" },
  { nameEn: "Central African Republic", nameFr: "R\u00e9publique centrafricaine", code: "CAF", codeAlpha2: "CF", continent: "AFRICA" },
  { nameEn: "Canada", nameFr: "Canada", code: "CAN", codeAlpha2: "CA", continent: "AMERICAS" },
  { nameEn: "Switzerland", nameFr: "Suisse", code: "CHE", codeAlpha2: "CH", continent: "EUROPE" },
  { nameEn: "Chile", nameFr: "Chili", code: "CHL", codeAlpha2: "CL", continent: "AMERICAS" },
  { nameEn: "China", nameFr: "Chine", code: "CHN", codeAlpha2: "CN", continent: "ASIA" },
  { nameEn: "Ivory Coast", nameFr: "C\u00f4te d'Ivoire", code: "CIV", codeAlpha2: "CI", continent: "AFRICA" },
  { nameEn: "Cameroon", nameFr: "Cameroun", code: "CMR", codeAlpha2: "CM", continent: "AFRICA" },
  { nameEn: "Democratic Republic of the Congo", nameFr: "R\u00e9publique d\u00e9mocratique du Congo", code: "COD", codeAlpha2: "CD", continent: "AFRICA" },
  { nameEn: "Republic of the Congo", nameFr: "R\u00e9publique du Congo", code: "COG", codeAlpha2: "CG", continent: "AFRICA" },
  { nameEn: "Colombia", nameFr: "Colombie", code: "COL", codeAlpha2: "CO", continent: "AMERICAS" },
  { nameEn: "Costa Rica", nameFr: "Costa Rica", code: "CRI", codeAlpha2: "CR", continent: "AMERICAS" },
  { nameEn: "Cuba", nameFr: "Cuba", code: "CUB", codeAlpha2: "CU", continent: "AMERICAS" },
  { nameEn: "Cyprus", nameFr: "Chypre", code: "CYP", codeAlpha2: "CY", continent: "ASIA" },
  { nameEn: "Czech Republic", nameFr: "R\u00e9publique tch\u00e8que", code: "CZE", codeAlpha2: "CZ", continent: "EUROPE" },
  { nameEn: "Germany", nameFr: "Allemagne", code: "DEU", codeAlpha2: "DE", continent: "EUROPE" },
  { nameEn: "Djibouti", nameFr: "Djibouti", code: "DJI", codeAlpha2: "DJ", continent: "AFRICA" },
  { nameEn: "Denmark", nameFr: "Danemark", code: "DNK", codeAlpha2: "DK", continent: "EUROPE" },
  { nameEn: "Dominican Republic", nameFr: "R\u00e9publique dominicaine", code: "DOM", codeAlpha2: "DO", continent: "AMERICAS" },
  { nameEn: "Algeria", nameFr: "Alg\u00e9rie", code: "DZA", codeAlpha2: "DZ", continent: "AFRICA" },
  { nameEn: "Ecuador", nameFr: "\u00c9quateur", code: "ECU", codeAlpha2: "EC", continent: "AMERICAS" },
  { nameEn: "Egypt", nameFr: "\u00c9gypte", code: "EGY", codeAlpha2: "EG", continent: "AFRICA" },
  { nameEn: "Eritrea", nameFr: "\u00c9rythr\u00e9e", code: "ERI", codeAlpha2: "ER", continent: "AFRICA" },
  { nameEn: "Spain", nameFr: "Espagne", code: "ESP", codeAlpha2: "ES", continent: "EUROPE" },
  { nameEn: "Estonia", nameFr: "Estonie", code: "EST", codeAlpha2: "EE", continent: "EUROPE" },
  { nameEn: "Ethiopia", nameFr: "\u00c9thiopie", code: "ETH", codeAlpha2: "ET", continent: "AFRICA" },
  { nameEn: "Finland", nameFr: "Finlande", code: "FIN", codeAlpha2: "FI", continent: "EUROPE" },
  { nameEn: "Fiji", nameFr: "Fidji", code: "FJI", codeAlpha2: "FJ", continent: "OCEANIA" },
  { nameEn: "Falkland Islands", nameFr: "\u00celes Malouines", code: "FLK", codeAlpha2: "FK", continent: "AMERICAS" },
  { nameEn: "France", nameFr: "France", code: "FRA", codeAlpha2: "FR", continent: "EUROPE" },
  { nameEn: "Gabon", nameFr: "Gabon", code: "GAB", codeAlpha2: "GA", continent: "AFRICA" },
  { nameEn: "United Kingdom", nameFr: "Royaume-Uni", code: "GBR", codeAlpha2: "GB", continent: "EUROPE" },
  { nameEn: "Georgia", nameFr: "G\u00e9orgie", code: "GEO", codeAlpha2: "GE", continent: "ASIA" },
  { nameEn: "Ghana", nameFr: "Ghana", code: "GHA", codeAlpha2: "GH", continent: "AFRICA" },
  { nameEn: "Guinea", nameFr: "Guin\u00e9e", code: "GIN", codeAlpha2: "GN", continent: "AFRICA" },
  { nameEn: "Gambia", nameFr: "Gambie", code: "GMB", codeAlpha2: "GM", continent: "AFRICA" },
  { nameEn: "Guinea-Bissau", nameFr: "Guin\u00e9e-Bissau", code: "GNB", codeAlpha2: "GW", continent: "AFRICA" },
  { nameEn: "Equatorial Guinea", nameFr: "Guin\u00e9e \u00e9quatoriale", code: "GNQ", codeAlpha2: "GQ", continent: "AFRICA" },
  { nameEn: "Greece", nameFr: "Gr\u00e8ce", code: "GRC", codeAlpha2: "GR", continent: "EUROPE" },
  { nameEn: "Greenland", nameFr: "Groenland", code: "GRL", codeAlpha2: "GL", continent: "AMERICAS" },
  { nameEn: "Guatemala", nameFr: "Guatemala", code: "GTM", codeAlpha2: "GT", continent: "AMERICAS" },
  { nameEn: "Guyana", nameFr: "Guyana", code: "GUY", codeAlpha2: "GY", continent: "AMERICAS" },
  { nameEn: "Honduras", nameFr: "Honduras", code: "HND", codeAlpha2: "HN", continent: "AMERICAS" },
  { nameEn: "Croatia", nameFr: "Croatie", code: "HRV", codeAlpha2: "HR", continent: "EUROPE" },
  { nameEn: "Haiti", nameFr: "Ha\u00efti", code: "HTI", codeAlpha2: "HT", continent: "AMERICAS" },
  { nameEn: "Hungary", nameFr: "Hongrie", code: "HUN", codeAlpha2: "HU", continent: "EUROPE" },
  { nameEn: "Indonesia", nameFr: "Indon\u00e9sie", code: "IDN", codeAlpha2: "ID", continent: "ASIA" },
  { nameEn: "India", nameFr: "Inde", code: "IND", codeAlpha2: "IN", continent: "ASIA" },
  { nameEn: "Ireland", nameFr: "Irlande", code: "IRL", codeAlpha2: "IE", continent: "EUROPE" },
  { nameEn: "Iran", nameFr: "Iran", code: "IRN", codeAlpha2: "IR", continent: "ASIA" },
  { nameEn: "Iraq", nameFr: "Irak", code: "IRQ", codeAlpha2: "IQ", continent: "ASIA" },
  { nameEn: "Iceland", nameFr: "Islande", code: "ISL", codeAlpha2: "IS", continent: "EUROPE" },
  { nameEn: "Israel", nameFr: "Isra\u00ebl", code: "ISR", codeAlpha2: "IL", continent: "ASIA" },
  { nameEn: "Italy", nameFr: "Italie", code: "ITA", codeAlpha2: "IT", continent: "EUROPE" },
  { nameEn: "Jamaica", nameFr: "Jama\u00efque", code: "JAM", codeAlpha2: "JM", continent: "AMERICAS" },
  { nameEn: "Jordan", nameFr: "Jordanie", code: "JOR", codeAlpha2: "JO", continent: "ASIA" },
  { nameEn: "Japan", nameFr: "Japon", code: "JPN", codeAlpha2: "JP", continent: "ASIA" },
  { nameEn: "Kazakhstan", nameFr: "Kazakhstan", code: "KAZ", codeAlpha2: "KZ", continent: "ASIA" },
  { nameEn: "Kenya", nameFr: "Kenya", code: "KEN", codeAlpha2: "KE", continent: "AFRICA" },
  { nameEn: "Kyrgyzstan", nameFr: "Kirghizistan", code: "KGZ", codeAlpha2: "KG", continent: "ASIA" },
  { nameEn: "Cambodia", nameFr: "Cambodge", code: "KHM", codeAlpha2: "KH", continent: "ASIA" },
  { nameEn: "South Korea", nameFr: "Cor\u00e9e du Sud", code: "KOR", codeAlpha2: "KR", continent: "ASIA" },
  { nameEn: "Kuwait", nameFr: "Kowe\u00eft", code: "KWT", codeAlpha2: "KW", continent: "ASIA" },
  { nameEn: "Laos", nameFr: "Laos", code: "LAO", codeAlpha2: "LA", continent: "ASIA" },
  { nameEn: "Lebanon", nameFr: "Liban", code: "LBN", codeAlpha2: "LB", continent: "ASIA" },
  { nameEn: "Liberia", nameFr: "Liberia", code: "LBR", codeAlpha2: "LR", continent: "AFRICA" },
  { nameEn: "Libya", nameFr: "Libye", code: "LBY", codeAlpha2: "LY", continent: "AFRICA" },
  { nameEn: "Sri Lanka", nameFr: "Sri Lanka", code: "LKA", codeAlpha2: "LK", continent: "ASIA" },
  { nameEn: "Lesotho", nameFr: "Lesotho", code: "LSO", codeAlpha2: "LS", continent: "AFRICA" },
  { nameEn: "Lithuania", nameFr: "Lituanie", code: "LTU", codeAlpha2: "LT", continent: "EUROPE" },
  { nameEn: "Luxembourg", nameFr: "Luxembourg", code: "LUX", codeAlpha2: "LU", continent: "EUROPE" },
  { nameEn: "Latvia", nameFr: "Lettonie", code: "LVA", codeAlpha2: "LV", continent: "EUROPE" },
  { nameEn: "Morocco", nameFr: "Maroc", code: "MAR", codeAlpha2: "MA", continent: "AFRICA" },
  { nameEn: "Moldova", nameFr: "Moldavie", code: "MDA", codeAlpha2: "MD", continent: "EUROPE" },
  { nameEn: "Madagascar", nameFr: "Madagascar", code: "MDG", codeAlpha2: "MG", continent: "AFRICA" },
  { nameEn: "Mexico", nameFr: "Mexique", code: "MEX", codeAlpha2: "MX", continent: "AMERICAS" },
  { nameEn: "Macedonia", nameFr: "Mac\u00e9doine du Nord", code: "MKD", codeAlpha2: "MK", continent: "EUROPE" },
  { nameEn: "Mali", nameFr: "Mali", code: "MLI", codeAlpha2: "ML", continent: "AFRICA" },
  { nameEn: "Myanmar", nameFr: "Myanmar", code: "MMR", codeAlpha2: "MM", continent: "ASIA" },
  { nameEn: "Montenegro", nameFr: "Mont\u00e9n\u00e9gro", code: "MNE", codeAlpha2: "ME", continent: "EUROPE" },
  { nameEn: "Mongolia", nameFr: "Mongolie", code: "MNG", codeAlpha2: "MN", continent: "ASIA" },
  { nameEn: "Mozambique", nameFr: "Mozambique", code: "MOZ", codeAlpha2: "MZ", continent: "AFRICA" },
  { nameEn: "Mauritania", nameFr: "Mauritanie", code: "MRT", codeAlpha2: "MR", continent: "AFRICA" },
  { nameEn: "Malawi", nameFr: "Malawi", code: "MWI", codeAlpha2: "MW", continent: "AFRICA" },
  { nameEn: "Malaysia", nameFr: "Malaisie", code: "MYS", codeAlpha2: "MY", continent: "ASIA" },
  { nameEn: "Namibia", nameFr: "Namibie", code: "NAM", codeAlpha2: "NA", continent: "AFRICA" },
  { nameEn: "New Caledonia", nameFr: "Nouvelle-Cal\u00e9donie", code: "NCL", codeAlpha2: "NC", continent: "OCEANIA" },
  { nameEn: "Niger", nameFr: "Niger", code: "NER", codeAlpha2: "NE", continent: "AFRICA" },
  { nameEn: "Nigeria", nameFr: "Nigeria", code: "NGA", codeAlpha2: "NG", continent: "AFRICA" },
  { nameEn: "Nicaragua", nameFr: "Nicaragua", code: "NIC", codeAlpha2: "NI", continent: "AMERICAS" },
  { nameEn: "Netherlands", nameFr: "Pays-Bas", code: "NLD", codeAlpha2: "NL", continent: "EUROPE" },
  { nameEn: "Norway", nameFr: "Norv\u00e8ge", code: "NOR", codeAlpha2: "NO", continent: "EUROPE" },
  { nameEn: "Nepal", nameFr: "N\u00e9pal", code: "NPL", codeAlpha2: "NP", continent: "ASIA" },
  { nameEn: "New Zealand", nameFr: "Nouvelle-Z\u00e9lande", code: "NZL", codeAlpha2: "NZ", continent: "OCEANIA" },
  { nameEn: "Oman", nameFr: "Oman", code: "OMN", codeAlpha2: "OM", continent: "ASIA" },
  { nameEn: "Pakistan", nameFr: "Pakistan", code: "PAK", codeAlpha2: "PK", continent: "ASIA" },
  { nameEn: "Panama", nameFr: "Panama", code: "PAN", codeAlpha2: "PA", continent: "AMERICAS" },
  { nameEn: "Peru", nameFr: "P\u00e9rou", code: "PER", codeAlpha2: "PE", continent: "AMERICAS" },
  { nameEn: "Philippines", nameFr: "Philippines", code: "PHL", codeAlpha2: "PH", continent: "ASIA" },
  { nameEn: "Papua New Guinea", nameFr: "Papouasie-Nouvelle-Guin\u00e9e", code: "PNG", codeAlpha2: "PG", continent: "OCEANIA" },
  { nameEn: "Poland", nameFr: "Pologne", code: "POL", codeAlpha2: "PL", continent: "EUROPE" },
  { nameEn: "Puerto Rico", nameFr: "Porto Rico", code: "PRI", codeAlpha2: "PR", continent: "AMERICAS" },
  { nameEn: "North Korea", nameFr: "Cor\u00e9e du Nord", code: "PRK", codeAlpha2: "KP", continent: "ASIA" },
  { nameEn: "Portugal", nameFr: "Portugal", code: "PRT", codeAlpha2: "PT", continent: "EUROPE" },
  { nameEn: "Paraguay", nameFr: "Paraguay", code: "PRY", codeAlpha2: "PY", continent: "AMERICAS" },
  { nameEn: "Qatar", nameFr: "Qatar", code: "QAT", codeAlpha2: "QA", continent: "ASIA" },
  { nameEn: "Romania", nameFr: "Roumanie", code: "ROU", codeAlpha2: "RO", continent: "EUROPE" },
  { nameEn: "Russia", nameFr: "Russie", code: "RUS", codeAlpha2: "RU", continent: "EUROPE" },
  { nameEn: "Rwanda", nameFr: "Rwanda", code: "RWA", codeAlpha2: "RW", continent: "AFRICA" },
  { nameEn: "Saudi Arabia", nameFr: "Arabie saoudite", code: "SAU", codeAlpha2: "SA", continent: "ASIA" },
  { nameEn: "Sudan", nameFr: "Soudan", code: "SDN", codeAlpha2: "SD", continent: "AFRICA" },
  { nameEn: "Senegal", nameFr: "S\u00e9n\u00e9gal", code: "SEN", codeAlpha2: "SN", continent: "AFRICA" },
  { nameEn: "Solomon Islands", nameFr: "\u00celes Salomon", code: "SLB", codeAlpha2: "SB", continent: "OCEANIA" },
  { nameEn: "Sierra Leone", nameFr: "Sierra Leone", code: "SLE", codeAlpha2: "SL", continent: "AFRICA" },
  { nameEn: "El Salvador", nameFr: "Salvador", code: "SLV", codeAlpha2: "SV", continent: "AMERICAS" },
  { nameEn: "Somalia", nameFr: "Somalie", code: "SOM", codeAlpha2: "SO", continent: "AFRICA" },
  { nameEn: "Serbia", nameFr: "Serbie", code: "SRB", codeAlpha2: "RS", continent: "EUROPE" },
  { nameEn: "Suriname", nameFr: "Suriname", code: "SUR", codeAlpha2: "SR", continent: "AMERICAS" },
  { nameEn: "Slovakia", nameFr: "Slovaquie", code: "SVK", codeAlpha2: "SK", continent: "EUROPE" },
  { nameEn: "Slovenia", nameFr: "Slov\u00e9nie", code: "SVN", codeAlpha2: "SI", continent: "EUROPE" },
  { nameEn: "Sweden", nameFr: "Su\u00e8de", code: "SWE", codeAlpha2: "SE", continent: "EUROPE" },
  { nameEn: "Swaziland", nameFr: "Eswatini", code: "SWZ", codeAlpha2: "SZ", continent: "AFRICA" },
  { nameEn: "Syria", nameFr: "Syrie", code: "SYR", codeAlpha2: "SY", continent: "ASIA" },
  { nameEn: "Chad", nameFr: "Tchad", code: "TCD", codeAlpha2: "TD", continent: "AFRICA" },
  { nameEn: "Togo", nameFr: "Togo", code: "TGO", codeAlpha2: "TG", continent: "AFRICA" },
  { nameEn: "Thailand", nameFr: "Tha\u00eflande", code: "THA", codeAlpha2: "TH", continent: "ASIA" },
  { nameEn: "Tajikistan", nameFr: "Tadjikistan", code: "TJK", codeAlpha2: "TJ", continent: "ASIA" },
  { nameEn: "Turkmenistan", nameFr: "Turkm\u00e9nistan", code: "TKM", codeAlpha2: "TM", continent: "ASIA" },
  { nameEn: "East Timor", nameFr: "Timor oriental", code: "TLS", codeAlpha2: "TL", continent: "ASIA" },
  { nameEn: "Trinidad and Tobago", nameFr: "Trinit\u00e9-et-Tobago", code: "TTO", codeAlpha2: "TT", continent: "AMERICAS" },
  { nameEn: "Tunisia", nameFr: "Tunisie", code: "TUN", codeAlpha2: "TN", continent: "AFRICA" },
  { nameEn: "Turkey", nameFr: "Turquie", code: "TUR", codeAlpha2: "TR", continent: "ASIA" },
  { nameEn: "Taiwan", nameFr: "Ta\u00efwan", code: "TWN", codeAlpha2: "TW", continent: "ASIA" },
  { nameEn: "Tanzania", nameFr: "Tanzanie", code: "TZA", codeAlpha2: "TZ", continent: "AFRICA" },
  { nameEn: "Uganda", nameFr: "Ouganda", code: "UGA", codeAlpha2: "UG", continent: "AFRICA" },
  { nameEn: "Ukraine", nameFr: "Ukraine", code: "UKR", codeAlpha2: "UA", continent: "EUROPE" },
  { nameEn: "Uruguay", nameFr: "Uruguay", code: "URY", codeAlpha2: "UY", continent: "AMERICAS" },
  { nameEn: "United States", nameFr: "\u00c9tats-Unis", code: "USA", codeAlpha2: "US", continent: "AMERICAS" },
  { nameEn: "Uzbekistan", nameFr: "Ouzb\u00e9kistan", code: "UZB", codeAlpha2: "UZ", continent: "ASIA" },
  { nameEn: "Venezuela", nameFr: "Venezuela", code: "VEN", codeAlpha2: "VE", continent: "AMERICAS" },
  { nameEn: "Vietnam", nameFr: "Vi\u00eat Nam", code: "VNM", codeAlpha2: "VN", continent: "ASIA" },
  { nameEn: "Vanuatu", nameFr: "Vanuatu", code: "VUT", codeAlpha2: "VU", continent: "OCEANIA" },
  { nameEn: "Yemen", nameFr: "Y\u00e9men", code: "YEM", codeAlpha2: "YE", continent: "ASIA" },
  { nameEn: "South Africa", nameFr: "Afrique du Sud", code: "ZAF", codeAlpha2: "ZA", continent: "AFRICA" },
  { nameEn: "Zambia", nameFr: "Zambie", code: "ZMB", codeAlpha2: "ZM", continent: "AFRICA" },
  { nameEn: "Zimbabwe", nameFr: "Zimbabwe", code: "ZWE", codeAlpha2: "ZW", continent: "AFRICA" },
]

export function getCountriesByContinent(continent: Continent): Country[] {
  return countries.filter((c) => c.continent === continent)
}

const countriesByCode = new Map(countries.map((c) => [c.code, c]))

export function getCountriesByCodes(codes: string[]): Country[] {
  return codes
    .map((code) => countriesByCode.get(code))
    .filter((c): c is Country => c != null)
}
