export const DesignSystem = {
  border: {
    color: "#040F0F",
    width: 1,
    radius: 8,
  },
  backgroundColor: "#F0F0F0",
  fontFamily: {
    regular: "Kuzfam",
    black: "KuzfamBlack",
    blackItalic: "KuzfamBlackItalic",
    bold: "KuzfamBold",
    boldItalic: "KuzfamBoldItalic",
    extraBold: "KuzfamExtraBold",
    extraBoldItalic: "KuzfamExtraBoldItalic",
    italic: "KuzfamItalic",
    medium: "KuzfamMedium",
    mediumItalic: "KuzfamMediumItalic",
    semiBold: "KuzfamSemiBold",
    semiBoldItalic: "KuzfamSemiBoldItalic",
  },
  fontSize: {
    xl: 22,
    large: 16,
    medium: 14,
    small: 12,
  },
  fontWeight: {
    normal: "400",
    semiBold: "600",
    bold: "800",
  },
  colors: {
    primary: "#1D70A2",
    secondary: "#50555C",
    success: "#4CAF50",
    danger: "#F44336",
    warning: "#FF9800",
    info: "#2196F3",
    light: "#F0F0F0",
  },
};
